const INPUT = {b:"13-14 f: ffffffffnfffvv\n" +
        "10-12 w: kwtzpnzspwwwdz\n" +
        "2-3 n: nnjn\n" +
        "2-3 h: hhhh\n" +
        "2-11 c: crccccccccsccc\n" +
        "1-6 b: lcpcbcr\n" +
        "16-20 q: qsqqqqqqqjqqqvqqqqqh\n" +
        "4-5 m: mmfmm\n" +
        "10-13 h: hhhhhhchhkhhphh\n" +
        "10-14 x: xxvxxxxxxvxxxwx\n" +
        "2-7 v: tvvgvrvvv\n" +
        "8-11 j: jjjjrjwljjzjkmc\n" +
        "2-5 t: xtpftb\n" +
        "4-6 m: mmmlmpm\n" +
        "9-14 h: hhhhhhhhhhhhhchh\n" +
        "10-11 x: xxxxxxxxxxx\n" +
        "14-15 z: zzzzzzpzzzzzzzkz\n" +
        "5-6 m: mwjmmw\n" +
        "2-4 r: rrrr\n" +
        "7-11 v: vvkwlmvkvkmbwvvvv\n" +
        "16-17 j: jjjjjjjjjjjjjjjhj\n" +
        "6-12 v: vjvvddtdpvvvldvqvdhv\n" +
        "3-16 z: rktsvbkctznjkjzz\n" +
        "5-6 r: hrrrrr\n" +
        "1-3 d: ddxddd\n" +
        "19-20 s: sssssjssssssssssssss\n" +
        "17-20 b: bbbbbbbbbbbbbbbbbbbb\n" +
        "2-4 m: mslm\n" +
        "2-5 b: bbbbbl\n" +
        "3-4 j: ljjj\n" +
        "2-4 h: nlhbh\n" +
        "4-5 z: zsmwfz\n" +
        "4-5 j: jjzqj\n" +
        "9-10 r: rrrrrrrrrj\n" +
        "7-18 l: lljlgpmlltlzjltplln\n" +
        "1-6 l: zbmljsljdszwl\n" +
        "3-6 h: hhfhhqhhh\n" +
        "10-14 d: vmddcdhsdzkxdddddddd\n" +
        "6-7 s: psssssms\n" +
        "1-10 j: cndjjjjjjjjjjj\n" +
        "4-14 x: xxxdxxxxxxxxxxc\n" +
        "6-7 f: fwfffsff\n" +
        "2-11 v: dmmvlvsvvbbr\n" +
        "7-8 l: dlcllllllll\n" +
        "4-5 m: mmmmc\n" +
        "4-10 m: zmmmlmnmrj\n" +
        "5-6 s: ssshdsvbsk\n" +
        "1-3 p: pppfps\n" +
        "5-6 t: tttttt\n" +
        "6-15 z: zzzzzzzzzzzzzzzzz\n" +
        "7-12 m: bgshdmmkmmmmmfnmmm\n" +
        "10-11 l: gclgllsllll\n" +
        "3-4 d: dpdd\n" +
        "2-9 n: kgngnrcxd\n" +
        "8-10 n: knnsqnnnnrn\n" +
        "8-18 f: qhwqbwnfppkffwhjjxf\n" +
        "2-4 j: zwksc\n" +
        "3-11 s: nkszjxwhcms\n" +
        "8-11 b: tbbbbbbwbmbjk\n" +
        "7-8 z: kvxfrzzzz\n" +
        "2-5 g: hhwgv\n" +
        "1-5 s: lmkxjbbsmnq\n" +
        "2-7 p: spgxbpp\n" +
        "2-8 z: xqzpztbvk\n" +
        "4-7 r: wrtcfqrqcrlr\n" +
        "2-4 g: gzgggg\n" +
        "13-15 q: qqqqnrqqqbgqnqt\n" +
        "7-12 h: dhxhbcqhhhhd\n" +
        "7-8 l: llllflll\n" +
        "5-6 d: ddbdfddwmndc\n" +
        "3-10 j: jjjjjjcjjjj\n" +
        "16-17 x: jhmqjpbpxsttjpcxrz\n" +
        "7-14 j: jqjjjgjhjjmjjfjj\n" +
        "5-7 l: zllllll\n" +
        "9-13 d: dddddddxrdcsjdngbtd\n" +
        "13-14 k: kdwkhqkkkkkknkk\n" +
        "5-12 c: zcxwcbwfclccm\n" +
        "14-16 x: xxfxxxhxxxxmdxxxxx\n" +
        "10-11 x: xxxvxxxxxqxxxxxhx\n" +
        "6-11 d: ddddddddddtddd\n" +
        "1-3 j: bjbcj\n" +
        "8-10 p: pppptppzpp\n" +
        "3-7 z: zwldzgvztmbwwqwb\n" +
        "4-5 h: hhhrm\n" +
        "4-7 v: vvrvjvsz\n" +
        "2-4 w: prsdkgxw\n" +
        "1-4 q: fqqvqqqnm\n" +
        "5-6 k: kzjbpkkkzzktkc\n" +
        "12-15 s: ssvssssnsssdssgss\n" +
        "3-10 w: wwfcwcwwwrjww\n" +
        "6-7 t: thftndnvtztztb\n" +
        "1-6 w: qgzppbcdjbpwmsj\n" +
        "3-16 c: nccccfccrrcqhwcjck\n" +
        "7-10 b: bfscxbdbnb\n" +
        "4-14 x: xxrxsgxxwxptxxxdxdx\n" +
        "1-4 c: jccb\n" +
        "16-17 p: ppkppppppppppppwk\n" +
        "2-10 z: wqtzzbhzkv\n" +
        "9-10 b: bcbbqwcbbdvbzbfbsj\n" +
        "6-11 s: ssssswsssssg\n" +
        "3-7 c: wdcxzgtcrswqj\n" +
        "4-10 c: xszcrmcsxccbwccxwv\n" +
        "6-9 f: pffffffff\n" +
        "7-8 k: wkhkhdkkkkkkrbkk\n" +
        "3-4 q: cqqbqpg\n" +
        "3-15 s: sswvssssswssssh\n" +
        "19-20 k: kkkkkkkkkkkkkkdkkkkx\n" +
        "11-14 d: dddddddddddddnd\n" +
        "3-4 l: llll\n" +
        "3-4 t: bvtvtrr\n" +
        "13-16 b: bbbbbbbbbbbbbbbb\n" +
        "16-20 b: bbbbbbbbbbbbbbbkbbbw\n" +
        "10-11 v: vhvvvvvvvnvv\n" +
        "1-6 v: xsvmvvxvkvv\n" +
        "4-7 t: vttltqg\n" +
        "16-20 b: bbbbgsjbxkbbbbbbrbqb\n" +
        "15-17 c: ccccccchcccccxphcc\n" +
        "1-3 w: cmwbtnzwwlhr\n" +
        "2-16 j: njmqdfdsmrsptrjz\n" +
        "12-13 r: rrrrcrrrrrrdhr\n" +
        "11-14 j: jgjjjjjjjjtpjh\n" +
        "4-5 w: wwstw\n" +
        "5-6 w: mwrgwwmdwhzk\n" +
        "4-7 b: bbdlbbbbc\n" +
        "1-16 b: xbbhfbhbbbdbbdbbbbb\n" +
        "11-14 h: hhjhjhhhhhhzhh\n" +
        "2-3 t: jrtrt\n" +
        "5-6 w: pdwwww\n" +
        "5-16 m: mmhrmsvmxmvjdltm\n" +
        "15-17 b: rbdbbbbtbfbbxbbbbbbb\n" +
        "4-6 t: lzjtttqdpthkzrt\n" +
        "3-4 x: xcxxxxxxxxxx\n" +
        "15-16 z: zzzzzzzzzzzkzrcljz\n" +
        "15-20 b: bbbbbpbbmbbbbbbbbbbb\n" +
        "15-17 z: zzzzzzzzzzzzzcqnzzr\n" +
        "3-13 t: tntttttttttttt\n" +
        "6-10 s: jssmqsslsssddtg\n" +
        "9-10 p: ppppppppjp\n" +
        "9-14 d: sdxnfmpzlgvdcs\n" +
        "5-6 c: cccscvcc\n" +
        "2-4 r: rrrr\n" +
        "11-14 v: vvcvvmvvvpvvvjv\n" +
        "2-6 h: znfjphzqzdczp\n" +
        "5-12 j: msdjjbjbgjjjbl\n" +
        "4-7 h: hhhthkhhh\n" +
        "5-6 q: qqqqqc\n" +
        "18-20 q: pttqsnjcfchtfnqbjlqf\n" +
        "11-12 x: xxxxxxxxxxxq\n" +
        "5-6 j: xqbwjjcxjjljgj\n" +
        "7-14 g: pdkdbzgzjvdvwggpnnt\n" +
        "2-17 j: zhklmfrwspkgqbxjjdp\n" +
        "5-17 b: bbbnbkbbbgbbxvzxhb\n" +
        "6-8 b: bwhbbbbb\n" +
        "6-16 q: lgxlqsqqwwmqrqqfgp\n" +
        "16-20 j: jjjkjjjjjvjjjjjjwjjb\n" +
        "1-2 g: vggg\n" +
        "3-7 v: fvsvvxfvvv\n" +
        "5-8 q: vdqqqqqqcrqqxq\n" +
        "11-16 w: wwwwwwwwwwbwwwwnwww\n" +
        "5-7 s: swwzsss\n" +
        "3-6 d: hqwqcvdnqvh\n" +
        "2-7 h: hsqhthghhhh\n" +
        "4-9 d: dddtddddddd\n" +
        "8-9 d: ddddddddd\n" +
        "2-4 q: qqqsq\n" +
        "4-6 t: ttnlqt\n" +
        "4-6 s: sssszscs\n" +
        "2-7 l: ssfllslplqll\n" +
        "1-3 m: vmmlm\n" +
        "6-13 q: qtqqqrqqqqqqqqqq\n" +
        "2-10 d: zbldzlzssd\n" +
        "4-5 n: nnndq\n" +
        "8-18 b: wbbdgkvgscbdgqvxdj\n" +
        "5-6 r: srrtrrrrr\n" +
        "6-8 m: mmmmwbpm\n" +
        "11-14 h: hhhhhhhthhhhhm\n" +
        "2-4 p: pvpxpp\n" +
        "5-6 g: ggvgng\n" +
        "4-5 x: xxxtp\n" +
        "3-10 v: vbvvzvhvvvvmvbcvvwrv\n" +
        "11-13 d: ddddddddddxdldd\n" +
        "4-5 g: gggggggggggngfggg\n" +
        "7-8 j: jpjjjjhw\n" +
        "2-6 m: jmfrmmhhsgbmmm\n" +
        "6-10 v: vrvvvbvvvsv\n" +
        "8-15 c: cctrcccpccccgcc\n" +
        "14-16 d: ddddxdsdzwdddwdsddh\n" +
        "5-6 m: mmnmmb\n" +
        "2-6 d: dtwlswdnlkn\n" +
        "12-13 x: vldxvmxcnndzx\n" +
        "4-6 k: kkkxkm\n" +
        "1-4 p: pppp\n" +
        "11-16 b: bbbbbbbbbhdbxpbbbpb\n" +
        "1-5 j: jjjjjj\n" +
        "6-8 q: zqwdqszvqwqbrmhfqqm\n" +
        "2-5 q: nqqczhb\n" +
        "12-17 v: vvvvvvvvvvvtvvvvpv\n" +
        "1-3 w: wwlww\n" +
        "9-11 n: nbndcjnzntnvjnk\n" +
        "3-4 q: qqcr\n" +
        "15-17 p: plppppppppbppppplpp\n" +
        "1-2 c: cvdlsccrccldccvfcc\n" +
        "4-5 p: bpppcp\n" +
        "19-20 d: dddddddddsdddddddddd\n" +
        "2-4 t: bwbtmjbgkdlpjkrxt\n" +
        "2-5 l: llxdblrcvnpclt\n" +
        "11-13 b: bpbbbbbmbbbpbtcbbbzm\n" +
        "6-7 p: ppppppp\n" +
        "5-18 m: mqmmqpmmmmmwmpmzchms\n" +
        "3-6 g: ggggmggkgg\n" +
        "11-18 z: wjwlzzptzzzwbmzzgz\n" +
        "5-7 b: bbcxbfbwbbcn\n" +
        "4-5 p: szppp\n" +
        "2-12 b: bbbbbbbbbbbmbb\n" +
        "6-10 m: jmmmmwmtmfcwwxm\n" +
        "4-5 m: mrqzmmmptfkmch\n" +
        "13-15 q: qqqqqqlqqqqqqqqd\n" +
        "1-5 b: kbbbnb\n" +
        "4-5 t: qdtttszwwppbtllp\n" +
        "12-14 c: cccccccccccccm\n" +
        "4-5 g: gggdhg\n" +
        "1-4 b: wbtbb\n" +
        "3-6 d: ddrdgbdvdv\n" +
        "14-15 x: xxxxxxxgxxxxxvdx\n" +
        "13-18 l: lllllllllllllllllll\n" +
        "5-7 p: zjsxppv\n" +
        "4-13 v: vvvpvvvvvvvvf\n" +
        "17-19 q: qqqqqpcqpqqgqqqqqqmq\n" +
        "1-5 r: rlmrrr\n" +
        "8-9 j: jjjjjjjjw\n" +
        "2-4 q: dswq\n" +
        "16-17 z: zzzzzzzzzzzzzzzzzz\n" +
        "4-7 h: hhhzhhw\n" +
        "11-12 l: lllllhhpllllqlllln\n" +
        "11-12 h: hhhhdhhhhhrhh\n" +
        "3-4 j: pkthmjsjqx\n" +
        "15-18 b: bbbbbgbbbbbbbbbbbh\n" +
        "4-5 j: lsxklmdwmhj\n" +
        "1-2 p: pptp\n" +
        "8-10 g: fgggzrnggg\n" +
        "3-7 k: njkdhpkpqtqxhqwkp\n" +
        "10-11 l: llllllllllz\n" +
        "12-14 q: qjqhkqmqqwqgqcg\n" +
        "1-3 m: mmmm\n" +
        "8-19 c: dwzvhvbcpdbhcnrlcncx\n" +
        "3-7 x: xtxjljw\n" +
        "6-18 t: pttgnchttttttttqtt\n" +
        "3-4 p: pppxpp\n" +
        "15-16 k: kkkkkkkkkkkkkkvr\n" +
        "2-3 x: dxxmx\n" +
        "12-20 m: mmmmmjmmcmdmmmmmcmmm\n" +
        "6-13 h: sthvjhlhfhxlhb\n" +
        "4-5 t: pbrlttgmmwztxtrt\n" +
        "3-7 p: dpptmppp\n" +
        "7-9 p: hpppppppp\n" +
        "3-4 q: qdgqqq\n" +
        "1-4 c: cffcrkpdczhbj\n" +
        "1-8 d: cqdwddlrddd\n" +
        "9-10 n: gnkmnxnzmn\n" +
        "3-4 k: kkxx\n" +
        "1-7 d: vnddddn\n" +
        "8-12 l: jllnlcllllllllvllb\n" +
        "1-4 n: nnnnnhnnnn\n" +
        "9-12 s: tssssszsssssbt\n" +
        "8-13 h: nhnhdtkjbsfvbsh\n" +
        "2-4 v: qmvs\n" +
        "3-6 c: chcxccch\n" +
        "1-5 d: ddddd\n" +
        "11-15 l: pklllvllwlmlcklllll\n" +
        "1-3 v: dvkbwsgjzqzzjmznd\n" +
        "5-6 j: zjjjjjs\n" +
        "1-4 f: vbffrwfr\n" +
        "3-5 x: xxxxxrfdxmnbkrjbdzcx\n" +
        "16-19 s: spsssbmrpbwrhqssgft\n" +
        "13-15 v: vvvrvvvvbvvvvvv\n" +
        "6-9 q: lqfqgcwtdqzgrqqp\n" +
        "3-5 w: fwpwx\n" +
        "7-8 h: hnhschhfphjzphwh\n" +
        "2-6 r: rrrrrrr\n" +
        "8-10 h: hhrhzhhttm\n" +
        "9-16 w: wwwwwwwwfwwwwwwh\n" +
        "2-3 n: zbnfnlpcnjqftpv\n" +
        "14-17 k: rqwlkzqczczrlktcl\n" +
        "6-7 f: ffffffff\n" +
        "3-6 k: nndkjtpjzpmkkr\n" +
        "12-17 p: gpppbpmjpptpfnzpb\n" +
        "16-17 n: nnnpnnlnnnnnnmnnnnnn\n" +
        "4-6 r: rrsrwr\n" +
        "4-7 x: cnljrzcj\n" +
        "7-8 s: srgtqlmc\n" +
        "8-10 n: nnnnnnnvnn\n" +
        "2-5 g: ggqggb\n" +
        "7-8 h: hhqhgpxb\n" +
        "4-12 b: bxbchbbbbbbbb\n" +
        "2-4 z: qfzng\n" +
        "6-13 m: pcmmwdkmzlstn\n" +
        "3-4 v: qvdc\n" +
        "2-10 t: tktttttttmt\n" +
        "9-15 t: tttttttttttpttw\n" +
        "8-13 p: pppjpppkppdlv\n" +
        "6-9 g: gggggngqg\n" +
        "2-9 k: lzvkqkkkkk\n" +
        "8-12 h: ldpnjvchhshx\n" +
        "5-14 c: cccccvrccccdbccchjc\n" +
        "14-19 k: kkjksgrrkklhkkkkkkt\n" +
        "5-15 r: hrrrrrwmrlrgrlz\n" +
        "7-17 g: hbjtgsxbgrgggcjlk\n" +
        "4-6 q: lqcbqvzqrqzqxqnqd\n" +
        "5-8 x: xkdxsxxf\n" +
        "12-16 m: vxlfjgzgqhxmlvmmqmm\n" +
        "2-13 c: vccvjvqrgrsrqv\n" +
        "4-6 l: ltlrlpvnl\n" +
        "12-16 p: ppptdppppppcfppzpgsm\n" +
        "18-19 q: qfqpvwpwjqvlnrmvsqq\n" +
        "5-6 m: mmmmmh\n" +
        "6-7 m: mmmmsls\n" +
        "3-4 p: pvcg\n" +
        "6-7 h: hhhhhhj\n" +
        "1-4 g: gkggc\n" +
        "3-10 n: sqsndtgnjbnljnn\n" +
        "5-11 h: tcmlhlnbfnhgt\n" +
        "9-10 t: ttttttttxl\n" +
        "6-8 x: mxvxxxxhxxccbx\n" +
        "9-16 g: rgggthgxggdggjgg\n" +
        "7-20 w: wwnwwhvmtwnvwwpzdxvt\n" +
        "13-14 t: tttmttlttgttlptt\n" +
        "5-6 f: ffffpg\n" +
        "5-7 z: qzzzzzqzz\n" +
        "1-3 b: bfbfdhkwdzttcldtr\n" +
        "5-8 n: nnnnrnnqnnnn\n" +
        "7-18 m: hgnrbdmvmzqmhnhhpww\n" +
        "2-6 h: rjghpwxhn\n" +
        "5-10 m: bjqjmmnbvmlxpvvdds\n" +
        "3-4 v: hvjttv\n" +
        "4-8 n: nnpnnnnnn\n" +
        "1-10 g: gzxghcgkggggtxg\n" +
        "4-6 b: pbgblbbb\n" +
        "4-7 c: ccccccmc\n" +
        "2-4 g: ggwgtzvxqhjqphfg\n" +
        "3-5 t: htdtt\n" +
        "8-9 t: tttttptttttt\n" +
        "4-5 v: dvvvd\n" +
        "6-12 p: skzhnpblmpppcptfpll\n" +
        "15-16 l: llllllllllllllvp\n" +
        "6-11 b: mbbbbjxbbmbbf\n" +
        "2-4 t: mtqwtnt\n" +
        "2-4 h: wfhkh\n" +
        "5-6 w: wwwlwwwkw\n" +
        "7-8 k: kskkkktz\n" +
        "5-6 g: rggqcv\n" +
        "2-4 z: krmw\n" +
        "2-4 q: qqwqlrqcbxlxbpqg\n" +
        "14-18 m: mmzmmmmnmmmmmtmmmm\n" +
        "1-5 p: pqwfpnp\n" +
        "3-7 w: dwwxdwgwwksm\n" +
        "8-11 g: bkmcfcddjvw\n" +
        "7-9 s: srsszspss\n" +
        "3-4 r: rjrsz\n" +
        "12-14 k: kkkkkkkkkkkgkl\n" +
        "13-14 f: fffffffffffffh\n" +
        "7-9 r: qgxpglrlr\n" +
        "4-6 l: xflkll\n" +
        "2-9 d: gdddddddrqdddd\n" +
        "2-3 k: zskkzq\n" +
        "3-4 z: jzrtwgmtl\n" +
        "3-4 b: bnnbbx\n" +
        "1-9 r: rhmrwwrfmsb\n" +
        "7-10 b: btbbbbbbjbbb\n" +
        "7-8 t: lmttpttq\n" +
        "1-4 s: rcls\n" +
        "11-12 k: kkkkklkkkskq\n" +
        "14-15 p: ppppppppppppppp\n" +
        "3-7 l: dcslvkjgjcdk\n" +
        "1-6 l: hllhllpl\n" +
        "6-9 z: zdlqztzzkzz\n" +
        "10-11 r: rrfrrrrrrrqjpkkrmrrh\n" +
        "4-5 v: bvpqvvkvrxnvzmghbhmx\n" +
        "10-11 v: vvvvvjvvfcvvcvpj\n" +
        "10-11 j: jjjsfhdmjtcvbzj\n" +
        "4-5 z: zzzzzz\n" +
        "14-15 l: lllllllllzlllkcnl\n" +
        "3-8 c: dchcjjrccvm\n" +
        "12-14 b: vrwbfbqbbbbkbhgqjjh\n" +
        "8-9 g: stggqgctgpgggctt\n" +
        "15-17 p: pppppppppppkppqpp\n" +
        "7-8 q: qqqjvqhmqq\n" +
        "3-4 x: xxxxx\n" +
        "7-8 g: ffbgglgzpjgqvnglpsgh\n" +
        "14-16 r: rrdrrrrrrrrrrgrrrd\n" +
        "10-13 l: lllllllllllll\n" +
        "6-14 q: qfqzqnqqmhqqsp\n" +
        "2-3 q: qqqqq\n" +
        "17-18 f: ffffffqfffffffffftf\n" +
        "11-13 h: hhhhhhhhhhmhz\n" +
        "3-10 c: cccmcccccfzc\n" +
        "8-12 v: vvvvvvvvvvvvrfwrvv\n" +
        "3-4 v: vrnx\n" +
        "1-12 v: gfvsvkvvvzvcvsv\n" +
        "9-10 b: lbtgbbpcfbgb\n" +
        "6-8 f: fgnffkfshhfbfc\n" +
        "8-10 w: wwwwwwwwgpltzwzk\n" +
        "7-12 b: btbbjbhbbpbbqsbbbvp\n" +
        "11-12 r: vfcvrrrzrhvc\n" +
        "19-20 g: gggggggggggggbggggjh\n" +
        "11-14 s: sfsvsfsswsssscxssm\n" +
        "4-6 c: lcclcc\n" +
        "7-8 g: gggggggr\n" +
        "10-14 g: gdcpmgxlgggggtgbgg\n" +
        "2-3 b: bktb\n" +
        "9-13 k: krkkkgkkkkvkkk\n" +
        "2-12 f: bwtgngzflzcfchx\n" +
        "2-4 m: mmmmmmm\n" +
        "10-12 b: bbbbbbbxbbblcbpb\n" +
        "3-4 c: ccct\n" +
        "6-8 r: kgqvrrrjn\n" +
        "10-12 f: ffffffwfffff\n" +
        "6-7 c: ckcjcjccc\n" +
        "10-12 l: lllltllllllxll\n" +
        "3-6 q: qqgqqlxqqq\n" +
        "4-5 b: nbbbbb\n" +
        "7-11 r: rrrrrrrrrrrrrrr\n" +
        "10-11 s: sssssssssss\n" +
        "1-6 w: wwwwwwwlww\n" +
        "5-7 l: lrlmlll\n" +
        "8-12 c: fbcmjxccqcwc\n" +
        "9-10 b: ljmbxwbbbbbhbbb\n" +
        "2-4 h: shwgvlw\n" +
        "15-17 t: ttptttttktttkttttt\n" +
        "2-5 d: dddgdd\n" +
        "2-14 x: xbbtnzdvbszrlxl\n" +
        "8-10 c: cccccccbcx\n" +
        "10-12 k: kkkkkkkkmkkc\n" +
        "7-17 r: rzbcshqhmrzrktzdr\n" +
        "5-16 k: kvkkdkkkkkkkkkklk\n" +
        "1-7 p: hkplfbjdhsh\n" +
        "1-6 z: pnzzzz\n" +
        "12-18 m: mmmjmxmmmmmmmmmmcd\n" +
        "5-7 k: kskkdbsk\n" +
        "9-10 b: bbbbgbbbbw\n" +
        "4-6 c: cccccjs\n" +
        "19-20 w: wwwwwwwwwwwwwwwwwwwf\n" +
        "7-11 j: drzjhxkjjjkwr\n" +
        "10-15 c: cccfckccccdccxc\n" +
        "1-3 d: ddddc\n" +
        "13-14 j: jbjjknjjjjjjjjjjjzzc\n" +
        "1-4 m: mzmftx\n" +
        "1-4 t: rttt\n" +
        "12-17 t: tltqttzttttjwcttrwtt\n" +
        "6-10 m: rmfmrnmmmdmqp\n" +
        "6-15 p: jpfpppwppppppznpppp\n" +
        "4-8 p: mppxctpb\n" +
        "2-4 z: gwzzrn\n" +
        "3-4 p: ppfpp\n" +
        "3-4 b: bbbh\n" +
        "11-17 l: llllllllllllllllhll\n" +
        "4-6 m: mmmmmmm\n" +
        "4-6 c: ccccjx\n" +
        "11-14 g: gggggggggggggg\n" +
        "3-4 l: llflq\n" +
        "9-13 p: pspvvcpkpcpzpfpk\n" +
        "1-4 n: nhwn\n" +
        "6-10 j: jjjjjjjjmjj\n" +
        "9-12 p: ppgpwxpplgppzpppwpp\n" +
        "10-14 h: hhhhhhfhhhhhmxh\n" +
        "8-10 l: llllllmcwfl\n" +
        "7-8 h: hhjhhhps\n" +
        "8-11 v: grvvvgbvxvvlhvvbdvr\n" +
        "5-6 m: fmjjbmp\n" +
        "1-2 x: xxhd\n" +
        "11-15 n: nnnnnnnnnncnnnm\n" +
        "1-8 g: jgggbggd\n" +
        "13-15 l: lshllllllllllll\n" +
        "5-12 r: crrsrrrrprtrr\n" +
        "10-16 k: hkkkkkkjkgtkkkkkq\n" +
        "5-16 j: prxjxjjdxzjjvjjwfj\n" +
        "7-8 k: pdkkkkkzkzw\n" +
        "3-4 s: sstg\n" +
        "1-5 x: vxxxb\n" +
        "10-16 s: tqmzsfksjzfmlqzsdb\n" +
        "2-5 r: rcrxjr\n" +
        "10-15 v: jcbvvvhvvvkwrgvvvvv\n" +
        "4-6 n: nnxnnpnn\n" +
        "13-18 l: llllllllllllbllllgl\n" +
        "9-11 g: vwqgnrzlclgqtp\n" +
        "2-3 f: fpms\n" +
        "3-5 l: llllllll\n" +
        "7-12 x: xcvxzxxhxxxxxxxxqxxv\n" +
        "6-10 b: fcfpwbmbhbpbbqkkbxb\n" +
        "8-11 z: nrnzzqzzzzck\n" +
        "8-9 g: nggdfgdgggfggg\n" +
        "2-6 d: sdztkkfvpkddggdxd\n" +
        "10-14 g: nhdstmlfxcggcs\n" +
        "10-11 g: ggzfglgggmcxgjh\n" +
        "3-13 x: cxjxxxxxxgxvj\n" +
        "9-10 h: smlxphtmkhf\n" +
        "7-8 v: rhdvgcvrdvvvvvxwvssh\n" +
        "7-14 n: nnnnnnncnnnvnn\n" +
        "3-6 z: zzzgznzz\n" +
        "6-10 l: llwmgllljllll\n" +
        "4-5 v: vwvvpvw\n" +
        "7-8 m: mmmmqvmqmv\n" +
        "13-14 z: zzzzzzzzzzhzrcz\n" +
        "3-8 h: bdmhcxpgbpjvwfmh\n" +
        "3-5 h: nhhjk\n" +
        "11-19 b: zrrmrqbfvwbnmvkvbzbv\n" +
        "3-8 c: ztwqhccmwzvcbxjjrc\n" +
        "4-9 h: hhhhhhhhh\n" +
        "2-15 d: lddzlxhkscrmfbd\n" +
        "3-9 s: kpscwnwzj\n" +
        "10-11 w: zwwlwxwwwwwwww\n" +
        "4-5 v: dpvjr\n" +
        "1-3 d: ddtd\n" +
        "3-6 x: xxdfxxxrbdh\n" +
        "3-6 g: dghwgxg\n" +
        "8-10 z: zzzzzzzpzz\n" +
        "13-15 p: pjpxpppppdcpphlppjp\n" +
        "6-16 j: jjjjjljnjjjjjqjjjwx\n" +
        "11-17 f: fffffffffflfpfffxff\n" +
        "8-10 j: jjjjjjlwjkjrdjjjj\n" +
        "8-9 w: wwwwfwwdkww\n" +
        "4-9 x: qpxbhxwxxkx\n" +
        "5-7 w: wwwwbwl\n" +
        "1-6 m: mmfrmmmm\n" +
        "8-9 l: lllllvlsl\n" +
        "3-4 d: dddd\n" +
        "6-8 c: cqcptcfcgcrzbjcccp\n" +
        "10-11 k: dccpkmkkgkkdzkkkkkk\n" +
        "3-4 j: jjjr\n" +
        "3-9 h: hzhwhchzhjg\n" +
        "7-8 g: bxgnvvzfsbggdgg\n" +
        "2-17 f: ffffffffffffffffffff\n" +
        "7-13 g: ljggdgztggvgtggg\n" +
        "9-13 x: rxlxrxxnwqxpcdxq\n" +
        "10-11 j: jjctjjjjjfjj\n" +
        "8-16 k: zpzskgkkkvsbxhsk\n" +
        "4-5 l: llljl\n" +
        "2-6 b: bbbbbb\n" +
        "1-3 w: swww\n" +
        "6-8 r: rrrrrbrbrr\n" +
        "8-9 t: tttttttth\n" +
        "3-5 s: sssss\n" +
        "3-14 q: qqxqqqqbblqqcqmqsq\n" +
        "7-8 v: dmfvccvvvbvmwjvvvqfv\n" +
        "5-7 v: qvvvvvvvv\n" +
        "4-9 c: cgcgvncctwrtv\n" +
        "3-5 p: ppnpppp\n" +
        "13-15 h: hhhhhhhhhhhhhhhhnhhh\n" +
        "5-8 r: rrrvpgrdbhrc\n" +
        "2-9 q: szlqwzwhqxbxkr\n" +
        "5-6 c: cwrmhxcpxchzccb\n" +
        "4-6 z: zzjczz\n" +
        "12-14 p: pwqkbphzplxhnpm\n" +
        "8-13 t: tkkzjttrstbtwttd\n" +
        "15-16 m: mmpqmxbxdzmqmmmb\n" +
        "4-6 c: ctcpczdd\n" +
        "2-3 j: fdjjj\n" +
        "15-19 k: kkkkkkkkkkkkkkpkkkwk\n" +
        "2-3 c: cccc\n" +
        "1-2 w: wwfqwwgpmv\n" +
        "2-3 h: wfzmhm\n" +
        "3-10 s: wbsbvhfxjgxfqstwqn\n" +
        "15-16 r: sxrzvkqpqmgzgtrr\n" +
        "3-5 m: fmmtmqjxzss\n" +
        "12-13 k: ddsnpkfvknhwq\n" +
        "5-11 z: lzwvzhtzzzz\n" +
        "12-13 t: tttttttttbdgtft\n" +
        "14-19 g: gggggggggggggggglgnv\n" +
        "3-4 r: rrrr\n" +
        "3-7 h: xchhnhh\n" +
        "10-11 n: ndnjnnhnnnk\n" +
        "5-7 l: llllhll\n" +
        "3-5 p: ppppb\n" +
        "11-12 s: rrsjzvswsdtxssv\n" +
        "2-10 z: ztxzzzzzztzp\n" +
        "16-17 m: mmmpmmmmmmmmmmmmmmq\n" +
        "1-6 b: wkbfntzw\n" +
        "10-14 n: nnnngrnnnnnnnnnn\n" +
        "1-3 b: pbdfsbbp\n" +
        "6-13 n: brnwnhnnsnnrwncnmz\n" +
        "2-11 f: mlhpdjflklzmhxt\n" +
        "1-2 f: shzsffl\n" +
        "8-16 k: kkkkkfkxfwnslkkm\n" +
        "13-14 b: bbbbbbbbbbkbqbb\n" +
        "2-7 x: zdxxxxxx\n" +
        "6-10 h: hhthmpvhnlk\n" +
        "6-7 p: tppfpqpcppppxpmpcpp\n" +
        "3-5 m: grmkm\n" +
        "5-11 w: vcwbwwwbwwswnrdwfwx\n" +
        "1-6 s: sssrssssx\n" +
        "13-14 j: jjjjjjjjjjjjgj\n" +
        "14-19 q: sbqqzqnqnlzdrlqqqtkl\n" +
        "3-4 t: btdttvzrvnjst\n" +
        "1-7 s: ssbsssmhssssdsc\n" +
        "3-4 z: vcdzj\n" +
        "6-13 v: vvvvvvvvvvvvvv\n" +
        "2-7 t: ttttgpthqhmth\n" +
        "5-9 z: zzzzwzzzl\n" +
        "10-15 w: wwwwckbzwwwwkwwlrwb\n" +
        "2-7 r: wjrbdzrjxrstrc\n" +
        "1-8 z: dpzzzvcsx\n" +
        "4-6 c: nccxccvcccczcccdc\n" +
        "1-10 c: cccccccccc\n" +
        "3-7 d: zdmdpdntdpzncdbff\n" +
        "5-9 x: xvlvxldrxxmbdcdxxxz\n" +
        "6-7 p: ppplppjcwcpp\n" +
        "2-7 d: pwnhpdd\n" +
        "2-3 q: hqqsdqxs\n" +
        "6-9 t: smttzjmktq\n" +
        "7-9 t: ttttttttp\n" +
        "4-19 w: wwwrwwwwwwwkwwwwwwnw\n" +
        "17-20 s: cssvssssssssssssssss\n" +
        "10-11 s: srssssssssss\n" +
        "5-6 f: ffcfjt\n" +
        "3-4 d: ddgdddddddd\n" +
        "2-15 s: sssssssssssstsssssss\n" +
        "2-4 c: kmccnnt\n" +
        "2-3 f: ffff\n" +
        "10-14 s: vspjssnsssssshvsq\n" +
        "9-10 k: skkkkkkfxkkwk\n" +
        "3-5 g: mgnggjpgspcf\n" +
        "4-15 z: zzzdzzzzzzzzzzzz\n" +
        "3-4 c: cgcc\n" +
        "6-7 s: sssssjs\n" +
        "2-4 z: ztzz\n" +
        "17-18 w: wbqwwnwwwmwvwwhgdnl\n" +
        "13-15 d: dwddddddddddwdddd\n" +
        "4-7 g: gzghgcnq\n" +
        "3-9 n: snnnnnmll\n" +
        "2-7 j: sjhtsxj\n" +
        "2-6 h: khvzdhhr\n" +
        "2-10 t: tttttttttttttttt\n" +
        "4-6 x: xxglxwjrx\n" +
        "3-4 r: rjrc\n" +
        "5-13 b: bbbbbbbdbbbbbb\n" +
        "3-4 q: qqrhqq\n" +
        "8-12 g: ggggkggdgggbg\n" +
        "3-12 j: jjjjjjjjjjjjjj\n" +
        "1-5 c: cbcch\n" +
        "10-11 r: rrnrvrrrrzn\n" +
        "4-16 j: jjjpjjjjhjjjjjrjjjv\n" +
        "8-9 f: fffffzdsvfccfr\n" +
        "14-16 f: ffzfjfftfffffffffff\n" +
        "2-8 n: ngnnnnntnnnnr\n" +
        "6-11 n: nchnnvnnnndn\n" +
        "4-5 w: sfwvm\n" +
        "6-14 s: ssssssvsspssqhsss\n" +
        "3-4 m: sjjb\n" +
        "2-4 d: dnkjd\n" +
        "3-9 s: twsgkmqstq\n" +
        "6-14 f: ffffffffffhfff\n" +
        "10-15 w: wmwlwwwwfgwwjrzwwwww\n" +
        "3-11 f: fffffkxfffffmfff\n" +
        "1-2 l: jlrpl\n" +
        "3-14 p: pbnpkbppxhppmpp\n" +
        "1-14 v: bvvvtvvvvbvvvh\n" +
        "3-4 s: zssvs\n" +
        "3-4 l: llljrlk\n" +
        "8-12 f: ffcfffczlffff\n" +
        "3-13 m: xsmgpvzsrrwmxtbktsrj\n" +
        "5-7 j: qxvjjlqjjjjj\n" +
        "3-4 r: rbdwg\n" +
        "13-14 d: dddddddddddddg\n" +
        "10-12 f: lqvhjnkfrfffv\n" +
        "6-7 n: njnnnhz\n" +
        "11-13 v: vvvvvvvvvvvvs\n" +
        "12-13 v: nvvsfvvvvvnvdvjxvvv\n" +
        "2-19 s: slsssssbsskspssssts\n" +
        "9-11 n: nnnnnnnnnnm\n" +
        "4-5 j: mhngjjrhjcjkjw\n" +
        "12-18 p: pnfwppppprsqrppltppp\n" +
        "9-13 s: wsssfsjsssfssss\n" +
        "6-8 b: bbbbbzbj\n" +
        "9-12 c: lcccccrccctv\n" +
        "7-11 w: wbdwwqwwkbwws\n" +
        "6-19 c: cccrmldccfhtvclcccc\n" +
        "9-14 h: bhhhhdhjkhhhhm\n" +
        "7-15 g: gkgggggvcgggghgggz\n" +
        "4-8 k: kknklwkkkg\n" +
        "10-13 c: ccccccxcccccccc\n" +
        "10-14 c: ccbcfcccptcczbcc\n" +
        "8-9 s: scsssssss\n" +
        "1-7 v: bvvvvvvvk\n" +
        "4-8 s: dspsskkstklsz\n" +
        "9-10 b: blbkkzbvvpbhbbbb\n" +
        "1-2 m: qgntnbccqm\n" +
        "7-14 w: wwwwlftgspwmwr\n" +
        "4-13 n: tnxmnnwwnnlnnnnz\n" +
        "3-5 c: cwzbs\n" +
        "3-6 d: dddddl\n" +
        "6-8 s: qsfssrnsst\n" +
        "1-2 l: llxcx\n" +
        "9-11 g: zhzkcbglvgw\n" +
        "5-11 f: lfzgtbcmzzw\n" +
        "6-19 m: gcbgjbqrdkswqhmxjct\n" +
        "1-3 z: dzzz\n" +
        "9-13 t: wttftcddttmtttgttnvt\n" +
        "14-15 z: zzzzgtzzwzzzzzzzzz\n" +
        "1-11 q: qqqqqqqqqqqq\n" +
        "4-5 j: rxjjjxjwjjj\n" +
        "3-5 v: gqjhjvlvlbmkgssd\n" +
        "16-17 q: qgcbftwncjhdzwqmw\n" +
        "1-3 g: tjftgp\n" +
        "11-16 l: rlllllllllgglllm\n" +
        "4-6 z: zprzvrfbpblf\n" +
        "7-11 j: jjjjjjjjhpjmjj\n" +
        "3-4 l: ltlrblllwljljlc\n" +
        "8-11 k: kkvkkkkkbqkskrkkd\n" +
        "5-10 r: hjrcrrrdvtrkrvrxrr\n" +
        "5-6 x: xxxxpx\n" +
        "13-16 g: gmggggggcggpwgghgt\n" +
        "3-4 h: hzzp\n" +
        "13-15 h: hhwhhghhhhhhhhh\n" +
        "3-5 t: mlftttt\n" +
        "8-13 c: cccccvcdccccfcccccc\n" +
        "1-6 k: kczzpq\n" +
        "8-14 t: rtcttttgtttttgtttz\n" +
        "6-7 l: lhsvlll\n" +
        "1-2 x: cxlr\n" +
        "8-10 t: rtbtttttsblttttb\n" +
        "11-14 z: zzzzzzzzzzdzzzz\n" +
        "2-3 t: ltttbthjdxwbxrv\n" +
        "5-6 x: xxxxxxxkx\n" +
        "8-12 f: fffffpffwfng\n" +
        "5-6 x: xxxxflxxxxx\n" +
        "5-7 d: ddddvvk\n" +
        "4-8 j: ttjjjjhj\n" +
        "2-5 p: rtrmpksjdvpplmrkl\n" +
        "9-11 s: ssshsskssssssr\n" +
        "5-8 j: wjnjjvjjfjjhf\n" +
        "4-6 q: qlpcjqqqq\n" +
        "13-14 m: zctdnmkjstxbmmfqtns\n" +
        "4-11 n: nqntnngnvmnknrnwnnl\n" +
        "3-5 d: ddfvdnkd\n" +
        "9-14 j: wsznlrpljmjwjjjkmtk\n" +
        "2-6 w: wlwwwww\n" +
        "9-12 j: jjzjxjjjjhjp\n" +
        "10-13 v: zvvvvvvvvfvwlvvvv\n" +
        "3-18 x: dzxcqgwxpwxvpmcxxdxx\n" +
        "2-3 w: wsgwwd\n" +
        "3-20 n: nrnfxnnnnlnnnnnfnrhp\n" +
        "3-8 f: fmvjwsffvxjfnlw\n" +
        "5-6 l: llllcs\n" +
        "3-5 b: bbbbbbc\n" +
        "2-7 l: rlwkflnsm\n" +
        "4-18 m: dqskhdqgmrpbgtmdnp\n" +
        "4-6 r: grpxzr\n" +
        "5-7 m: mmmmmmjmm\n" +
        "7-8 b: bbkkbbkbb\n" +
        "1-4 r: rwrtr\n" +
        "5-6 g: gggcggg\n" +
        "4-6 l: qlcbwrsf\n" +
        "16-18 t: tttmtttltvtttttxtrtt\n" +
        "3-4 z: zzzz\n" +
        "6-10 g: gggggtgggg\n" +
        "12-15 f: tffffffffqrffvvftffh\n" +
        "10-16 w: wwgwwpwhqdwhwpbw\n" +
        "5-7 m: mpmmmmm\n" +
        "3-5 b: bbxtbbb\n" +
        "5-10 x: xxxxbxxxkjkx\n" +
        "10-12 b: bjbldbbbwbxg\n" +
        "3-4 g: gnggqgg\n" +
        "2-4 s: sstst\n" +
        "6-10 j: jjjjfvjjjj\n" +
        "16-20 r: rrrrrrrrrrrrrrrrrrrr\n" +
        "4-12 b: bbbxbbbbbbbbbbbbb\n" +
        "3-4 k: kkpk\n" +
        "4-7 s: ssssqsh\n" +
        "10-13 b: vbzbbbbnblbbb\n" +
        "12-14 f: rgqffrfsvftwff\n" +
        "2-4 x: bfxvhmsxnqxz\n" +
        "10-12 c: ccccccccccbcc\n" +
        "1-4 l: llxbmjpll\n" +
        "9-14 f: ffhfmpfffffzfgcg\n" +
        "3-4 n: ndfm\n" +
        "1-6 k: lkmdzgfbkfktkkvkw\n" +
        "12-13 q: qtkqqgqbqtqgvqqqzq\n" +
        "7-9 d: ddddddhddsd\n" +
        "4-11 j: kdqjjjjjjxg\n" +
        "4-6 k: kkkgkm\n" +
        "6-12 n: nnnnndtnnnnnnv\n" +
        "2-6 c: dccccdc\n" +
        "10-11 v: vvvlvvvvvvb\n" +
        "7-10 w: wwwwwcwtzwkpvjqwsb\n" +
        "1-5 x: xxxxxxx\n" +
        "5-8 g: dhggzggsggggglgggg\n" +
        "8-9 t: dttttttdtfnt\n" +
        "11-17 g: cqgglgtwgggcbwjvwg\n" +
        "1-2 t: ttttt\n" +
        "16-17 j: jjjjjjjjjjjjjjjjjj\n" +
        "4-7 k: lkdkhkkkfk\n" +
        "15-17 z: zzzzszzzzzzzzzwzlz\n" +
        "3-13 w: wwswwwwwwwwwfwww\n" +
        "5-12 h: mstzhsghhhhnzmdrh\n" +
        "10-12 h: hhhhhhfhhphhbhhk\n" +
        "3-4 j: jjsd\n" +
        "11-12 k: kkkkkkmkkmfd\n" +
        "19-20 d: ddddhdddddddddddddxj\n" +
        "7-8 g: gggjggrg\n" +
        "4-5 m: mdzmv\n" +
        "3-4 w: wwww\n" +
        "7-8 b: bdbwbbbbb\n" +
        "2-12 q: dxqqqqqjqqqlqq\n" +
        "3-6 w: wwwwxwh\n" +
        "9-11 s: smhnkssssssstxj\n" +
        "5-6 n: nnpnkj\n" +
        "7-8 s: qsgdxkjs\n" +
        "9-14 m: mmmmmmmmsmmmmv\n" +
        "1-3 v: vvcvv\n" +
        "2-5 x: kzxgjttwxspclfx\n" +
        "5-8 c: ccctpcckz\n" +
        "5-6 h: hhhchthqxchh\n" +
        "3-7 t: hnrcqdtttmtxtnmhcf\n" +
        "2-4 v: vvlz\n" +
        "4-5 k: kbgkl\n" +
        "9-12 x: mhzpjqtxqnfrcnwhk\n" +
        "7-11 z: slztclzvxbzmz\n" +
        "13-14 l: ldllllllllllkcl\n" +
        "1-2 l: fslcthfv\n" +
        "12-16 b: bxbkbbbbbbbbbbbb\n" +
        "1-4 r: rrmr\n" +
        "8-11 d: dddfdpdddtdd\n" +
        "17-20 n: nnnsngnbnnnnnnnncnnn\n" +
        "1-16 x: xxxxxxxxxxxxxxxxx\n" +
        "2-4 z: zqzv\n" +
        "1-4 m: fnwm\n" +
        "2-3 j: jqvd\n" +
        "10-12 h: ghhhhhjhhchg\n" +
        "14-15 v: vvtvvvvvvvvvvvv\n" +
        "4-6 f: ffffff\n" +
        "8-20 g: tgghjfglrzggggcxhcgg\n" +
        "9-11 p: pvpmzppppkpk\n" +
        "5-18 x: xxxxnxxxxxxxxxxxwlzx\n" +
        "10-11 m: mgdmrfchqwmfmrlnq\n" +
        "7-8 g: gggggzxs\n" +
        "4-6 n: vjnchzknzbvnvn\n" +
        "17-18 p: pppppppppppkppppjp\n" +
        "6-8 d: dddddfddld\n" +
        "1-4 r: brrr\n" +
        "2-10 m: mzmmhqmmmmkmmwm\n" +
        "8-15 f: cfjwxkgmfkxdmwxf\n" +
        "3-8 c: djskjzcmwjcz\n" +
        "2-3 k: hkckkjbztrggrffvxwm\n" +
        "11-13 d: krddnddddrddgdddd\n" +
        "4-5 f: zjsndf\n" +
        "4-5 r: rrrgl\n" +
        "1-2 z: tsbn\n" +
        "1-11 s: sssdwtjssssskkszms\n" +
        "6-16 x: xfxxtxxxxxxdxzxmxx\n" +
        "5-13 m: mmmmmmmmmmmmmvm\n" +
        "2-4 z: zdzj\n" +
        "3-4 d: dddd\n" +
        "3-4 n: nnmnkv\n" +
        "14-16 d: dfddddddddddtddddqdd\n" +
        "5-7 n: jnnnnnnj\n" +
        "8-16 q: qqltjqqqqqqqsqqfq\n" +
        "10-14 s: sssxsmsssvqjssss\n" +
        "6-7 w: wwwwjwwxwd\n" +
        "2-5 m: mzqcndqmnmmgwmsspm\n" +
        "9-10 k: tkkkkrkkkhkk\n" +
        "3-5 r: rxrrrrr\n" +
        "7-11 c: glfcdqrcnfhc\n" +
        "8-9 r: rrrrrrrjd\n" +
        "7-8 d: ddddddlk\n" +
        "2-7 j: pjsmjjr\n" +
        "2-4 x: txxx\n" +
        "13-15 f: ddkhqfnbcmtwvbf\n" +
        "7-11 n: nnnnnnnnnnvn\n" +
        "7-9 m: jmmmlgmmthlrm\n" +
        "8-13 w: wwwwkwwgwwwwfrwww\n" +
        "2-6 d: drdrhn\n" +
        "8-10 k: lnkfrvgkzkchq\n" +
        "4-7 z: lxjzzzzhzprrzzzpcwj\n" +
        "1-2 s: lssc\n" +
        "2-3 n: jmkcngpn\n" +
        "3-9 x: xxmzxnxxxx\n" +
        "3-12 v: nqwshwqgfnwvwvnf\n" +
        "5-8 m: zmmmmmmmqlkprv\n" +
        "1-5 q: qpqrqwqsvpjqf\n" +
        "14-18 q: qqqqqqqtqqqcqqqqqq\n" +
        "13-16 v: vvvvhvvvvvvvrvxdv\n" +
        "2-6 r: rrlrrrk\n" +
        "6-8 r: hmsrxsrkprdrrrl\n" +
        "14-16 s: sssssslssgswssssss\n" +
        "3-11 t: ctttvsnfcstzktktb\n" +
        "1-11 c: gwfbddphwnqcmf\n" +
        "3-18 h: hhhhhhwhhhhhhhhhhs\n" +
        "7-9 c: cjjcrtpvctccfcc\n" +
        "6-14 f: fffffgfffffffff\n" +
        "8-15 z: zzzzzzzzzzzzzzdz\n" +
        "9-16 d: ddddbdddhddddqpd\n" +
        "1-2 q: qffc\n" +
        "3-5 l: grcsjln\n" +
        "12-13 q: qqqqqqqqqqqqq\n" +
        "4-5 q: qqqlk\n" +
        "1-3 w: wwwx\n" +
        "3-4 w: kwwf\n" +
        "5-15 m: pkwmgmmxspzxhmmrmp\n" +
        "5-18 t: ttfthsbwntpcnttmwtc\n" +
        "14-15 p: pjpjwppkpxpqkpf\n" +
        "1-3 n: nnnn\n" +
        "8-9 j: jjjjjjjbxj\n" +
        "4-6 w: gfhwfwwmfx\n" +
        "8-11 k: kkckkkknkkkk\n" +
        "13-14 m: mmmmmmmmmmmmsqmmm\n" +
        "2-4 s: tsrz\n" +
        "9-13 j: tjvjqpnjjjlkwjjljrj\n" +
        "3-4 f: xwfgf\n" +
        "2-7 h: rhxshbh\n" +
        "10-18 j: jjjjjjgbjjjjjjjjjjj\n" +
        "5-14 n: fnwnnnsnnnncnpnn\n" +
        "9-13 h: qhhlnhhhqhhhm\n" +
        "3-17 h: hhfgzkhhjhrbhwdcpbnh\n" +
        "2-4 c: qccrblqtcd\n" +
        "13-16 s: ssjssqssssqsxssw\n" +
        "10-15 n: nnnnnnnnnqnnnnf\n" +
        "2-3 m: nmtl\n" +
        "2-4 w: wqwdt\n" +
        "4-7 v: vvvvvvvvvvv\n" +
        "5-6 w: wbctwwwgj\n" +
        "4-6 q: qqqttqzzwsxp\n" +
        "2-7 r: rcrrrrrr\n" +
        "10-12 d: sdmddcfdddzvdddddq\n" +
        "1-15 f: ffffffffffffffffff\n" +
        "3-7 r: rrwddcjgr\n" +
        "2-11 t: tttttgttttttt\n" +
        "3-6 n: nhxgnqnnfs\n" +
        "1-3 t: pqtwt\n" +
        "8-17 r: rrrrrrrrrrrrrrrrrrrr\n" +
        "3-16 t: tktnpjtcthrhtqltq\n" +
        "5-6 h: kcmkkqdrbhhxm\n" +
        "3-4 l: llll\n" +
        "1-14 g: gggdgrvjtqfgpk\n" +
        "5-8 p: ppppplwcpp\n" +
        "4-7 d: ddddtdmdd\n" +
        "1-7 q: qqvxrqq\n" +
        "8-10 v: pvvvgkqrvvgnvlvv\n" +
        "17-19 g: sdgghgnggggggfbmggp\n" +
        "6-8 x: rvjknxlx\n" +
        "13-14 r: rrrrrrrrrrrrrb\n" +
        "3-10 b: zbkmbbbbbb\n" +
        "4-6 d: kdtbdmkd\n" +
        "8-12 m: mmzmmmmmcxmmh\n" +
        "7-8 n: gspnbfnp\n" +
        "13-14 l: llllllllllllnf\n" +
        "4-5 b: rzbbbxblvbwbrbbbx\n" +
        "3-5 x: bxgrcxxrk\n" +
        "2-4 j: jjjh\n" +
        "11-13 r: rrrrrrrrrfrrrrrrr\n" +
        "4-7 q: mwqqfqqqnwqwq\n" +
        "2-3 g: sghvhggvv\n" +
        "4-5 k: kkkkk\n" +
        "11-12 s: ssssssskssgss\n" +
        "16-17 g: dcgqnwtptvvlfkdgg\n" +
        "4-5 v: vvvqc\n" +
        "2-6 s: xsksrmrrd\n" +
        "7-8 w: swwwwwfnww\n" +
        "5-6 m: hmgchm\n" +
        "6-8 m: mmmglzmmmhfnfqk\n" +
        "2-5 c: bnjknt\n" +
        "2-3 x: lxxj\n" +
        "1-4 g: gqgpzgtj\n" +
        "3-12 c: cngsrcvcjccxgcc\n" +
        "2-11 z: zpzzzzzzzzzzz\n" +
        "6-7 s: ctsxgslsjbstspgsl\n" +
        "1-2 v: vnqs\n" +
        "4-5 n: rnnwcnfl\n" +
        "14-17 v: kvvvvvvvkvvvvbnvw\n" +
        "5-6 h: hhhchhh\n" +
        "1-7 d: vmcdddj\n" +
        "14-16 n: snnnnnnnnnnmnnnhn\n" +
        "11-16 h: hhhhhhvhdhrhhghn\n" +
        "3-5 k: lckkknk\n" +
        "1-12 t: tcttbpgtdwdxwddrxv\n" +
        "1-13 x: jxxxxxxxxxxxfx\n" +
        "11-12 l: llllflllllll\n" +
        "11-14 p: qpphckzdppkjxz\n" +
        "3-16 d: nfngxfjxwdpjvjcds\n" +
        "4-5 b: xkbmb\n" +
        "11-12 s: sssssssssshs\n" +
        "15-17 t: tttttttttttwttttt\n" +
        "14-15 x: xxxxxxxxxxxcxxgm\n" +
        "3-5 t: wxlttc\n" +
        "10-11 x: xxxxxxxxxtk\n" +
        "9-12 h: hhhhhhhhdhhhh\n" +
        "5-20 d: smdvdkdbqbnsdssfhdnd\n" +
        "16-17 d: ddddddddddddddsvtddl\n" +
        "6-11 v: kvvvvvvmvvdv\n" +
        "2-5 r: nrrgr\n" +
        "1-4 b: bbbc\n" +
        "8-10 p: ppppptjpspkpppp\n" +
        "7-10 w: pjhswvhdjqx\n" +
        "11-13 c: cfcfccbcctgnccccvcc\n" +
        "8-14 t: tttttttttgtttttts\n" +
        "1-4 c: fcccc\n" +
        "4-6 v: tvfvvvqvlkrpxkvvhztr\n" +
        "3-6 v: vvdvvbv\n" +
        "13-15 p: pwppppppppppppp\n" +
        "1-2 v: pwbr\n" +
        "15-18 r: xrrrbrrrgrpbrprrqrqr\n" +
        "2-4 g: zgggp"}.b
module.exports =  function main() {
    const lines = INPUT.split("\n");
    let ctr = 0;
    let ctr2 = 0; // for part 2
    for (const line of lines){
        //if (ctr > 5) return;

        const [,min,max,chr,pass] = (/^(\d*)-(\d*) ([a-z]): ([a-z]*)$/gm).exec(line);
        const count = (pass.match(new RegExp(chr, "g")) || []).length;

        if (count >= +min && count <= +max) {
            ctr++;
        }
        if (((pass[min-1]===chr) + (pass[max-1]===chr)) === 1){
            ctr2++;
        }
    }
    return [ctr, ctr2]
}