const INPUT = {b:"BFBFBBBRLL\n" +
        "BFFBBBBRRR\n" +
        "FFBBFBFLLL\n" +
        "FFBBBBBRLR\n" +
        "BFFBFBFRRL\n" +
        "BFFBFFBRLL\n" +
        "FBBFBFBRLL\n" +
        "FFBFFBBLLR\n" +
        "BFBBBFFRRR\n" +
        "FBFFFFBLLL\n" +
        "FFFFFFBRRR\n" +
        "FBBFBFFRRR\n" +
        "FFBBBBFRLL\n" +
        "BFFBBFBLRR\n" +
        "BFFFFBFRRL\n" +
        "FFFFFBFRLL\n" +
        "FBFFBFFRRR\n" +
        "BFBFBBBLLR\n" +
        "FBFFBBBLRR\n" +
        "FBBBBBFRLR\n" +
        "FFBFFBBRLR\n" +
        "FBBFFFFRRL\n" +
        "FFFFFBBRRL\n" +
        "FFBBFBFRLL\n" +
        "BFFBBBBLLL\n" +
        "FFFFBFFRRL\n" +
        "FBBFFFFLLR\n" +
        "FFBBBBBLLR\n" +
        "FBFBBFBRRR\n" +
        "FBFFBBFRRL\n" +
        "BFBFBFBRLL\n" +
        "BFFBBBBLLR\n" +
        "FBBBBFFLLR\n" +
        "FFBFBBFRLL\n" +
        "BBFFFFBRRL\n" +
        "FBFFFBBLLL\n" +
        "FFFFBBBLLR\n" +
        "FFBBFFFRLL\n" +
        "BFBFFBBRLL\n" +
        "FFBBBFBLLR\n" +
        "FFBBFFFRRR\n" +
        "BFFFBBBRLL\n" +
        "FBFBBFFRLR\n" +
        "FBBFBBBRRR\n" +
        "FBBBBBBRRR\n" +
        "BFFBFFFRRR\n" +
        "BFFBBBFLLL\n" +
        "BFBFFFBLLL\n" +
        "BFFBFBFLLR\n" +
        "FBFFFFBLRL\n" +
        "BFFBBFFLRR\n" +
        "BFBFBFFLLL\n" +
        "BBFFFBFLRL\n" +
        "BFFFBBBLLL\n" +
        "FFBBBBBLLL\n" +
        "BFFFFFFRLL\n" +
        "FFBBBBBLRL\n" +
        "FBFBBBBLLR\n" +
        "FFBBFBBLRL\n" +
        "FBBFBFBLRL\n" +
        "FBBFBBBLRR\n" +
        "BFFBFBBRRR\n" +
        "BFFBBFFLRL\n" +
        "FBFBBFFLLR\n" +
        "BFBBBFFLRR\n" +
        "FBBBFFBLRL\n" +
        "FBFBBBBRLL\n" +
        "FFFFBFFLLL\n" +
        "BBFFFBFRRR\n" +
        "BFBFBBFLRR\n" +
        "FBBFBFFLLL\n" +
        "FBBBBFBRRR\n" +
        "FFFFBBFRRR\n" +
        "FBBFFBFLLL\n" +
        "FBBBFFBRRR\n" +
        "BFFBBBBLRL\n" +
        "FFFFBFBRLL\n" +
        "FBBFFFBRRR\n" +
        "FBFBBFFRLL\n" +
        "BFFFFBFRRR\n" +
        "FFBBBFFLRR\n" +
        "FBBFBBFLLR\n" +
        "BBFFFFBRRR\n" +
        "BFFBFBFLLL\n" +
        "FFFBBBFLLR\n" +
        "FFBFFBFLRL\n" +
        "FFBFBBBLRL\n" +
        "FBFFFBBRRL\n" +
        "BFFBFBBLLR\n" +
        "BFBBFBBRLR\n" +
        "BFBBFFFRRL\n" +
        "FBFBFFFLLR\n" +
        "FFBBBFFLLR\n" +
        "BFBBBFFLLR\n" +
        "BFBFBFBLLR\n" +
        "BBFFFBFLLL\n" +
        "FFBBFBFRRR\n" +
        "BFFFBBFRRR\n" +
        "FBFFBBFRLR\n" +
        "BFBBBBFRLL\n" +
        "BBFFFFBLLR\n" +
        "FFFBFBBLLR\n" +
        "FBFFBFBRRR\n" +
        "FFBFBFBRRR\n" +
        "FFFFFBBRLL\n" +
        "BFFFFBFLLR\n" +
        "FBBFBBFLRR\n" +
        "FBFFFFFRRL\n" +
        "FBBFBFBLLR\n" +
        "BFFFFBBLLL\n" +
        "FBBBBBFLLL\n" +
        "FBBFFBFRRR\n" +
        "BBFFBFBLRL\n" +
        "BFFFBFFRRL\n" +
        "BFFFFFBLLR\n" +
        "FFFBBFBRLR\n" +
        "FBFFBFFRLR\n" +
        "BFBFBFFLLR\n" +
        "BFFFBBFLRL\n" +
        "FFFFBFFLLR\n" +
        "BFFBFFFRLR\n" +
        "FBFBFBFLRR\n" +
        "FBBBBBBRLR\n" +
        "BFBFBFFLRL\n" +
        "BFFFBFBLLR\n" +
        "BBFFBFFLLR\n" +
        "BFFBBBBLRR\n" +
        "FFFBBFFRRR\n" +
        "FBBFBBBLRL\n" +
        "FFBBBFBRLR\n" +
        "FBBBFBFRLR\n" +
        "FBBBBFFLRL\n" +
        "FFBFBFFRLR\n" +
        "BBFFFFFLRL\n" +
        "FFFBBBBLRL\n" +
        "FBFBBBFLRL\n" +
        "BFFBFFFRRL\n" +
        "FFBFFBFRLR\n" +
        "FBFBFFFLRR\n" +
        "FBFBFFBRRL\n" +
        "FBFBBBBLRL\n" +
        "BFBBBBBLLL\n" +
        "BBFFFFBLRR\n" +
        "BFFFBFFLRR\n" +
        "FBBBBBFRRR\n" +
        "FBFFBBBLRL\n" +
        "BBFFFBBRLL\n" +
        "BFBFBFBRRR\n" +
        "BFFBFBBLRR\n" +
        "FFBBFBBRLL\n" +
        "FFFFFBBRLR\n" +
        "BFFFBFBRRL\n" +
        "FFFBFBBLLL\n" +
        "FFFFBFBRRR\n" +
        "FBBFFBBLRR\n" +
        "BFFFFBBLRR\n" +
        "FFBFFFBLRL\n" +
        "FFBFBFBLRR\n" +
        "FBBBBFFRRR\n" +
        "FBFFBFBLRL\n" +
        "BFBFFBBLLL\n" +
        "FBBFFFFLLL\n" +
        "FBBFFBBLLR\n" +
        "FFBFBFFRLL\n" +
        "FBFBBBFRRR\n" +
        "BFFFBFFRLL\n" +
        "FFBFBFBRLL\n" +
        "FFBBFBFLRL\n" +
        "FFBBFBBLLR\n" +
        "FBFBBFBLRL\n" +
        "BBFFFFFRRR\n" +
        "FBBFFBBLRL\n" +
        "BFBFFBBLLR\n" +
        "FFFFFBBLLL\n" +
        "FFBBBBFRRL\n" +
        "FFBBFFFLLL\n" +
        "FFFBFFBRLL\n" +
        "FFBFBBFLLR\n" +
        "BFFFBBBRLR\n" +
        "FBFFBBFRRR\n" +
        "FBBFFFFRLL\n" +
        "FFFBBBFRLR\n" +
        "FFBBFFBRRR\n" +
        "BFBFFFFLRR\n" +
        "BBFFBBFLLR\n" +
        "BFFBFFBLRL\n" +
        "BBFFBFFLRR\n" +
        "FFFBFFBRRR\n" +
        "BFFFBBBLRR\n" +
        "BFBFFBFRLR\n" +
        "FFFBFFFRRR\n" +
        "FFBFBBBRLR\n" +
        "BFBFBBFRLR\n" +
        "BBFFBFFRRL\n" +
        "BFBFBFFRLR\n" +
        "FBBFFFFRLR\n" +
        "FBFBFBBRLL\n" +
        "FFBBBFBRLL\n" +
        "FFBFFFFRRR\n" +
        "BFFBFBBLRL\n" +
        "FFFBFBFRLR\n" +
        "FBBFFFBLRL\n" +
        "FFBFFFFLRL\n" +
        "BBFFBBFRLL\n" +
        "FFFFFFBRRL\n" +
        "BFFBFFBLRR\n" +
        "BFFFFFFRRL\n" +
        "BFFBBFBLRL\n" +
        "FBBFFFFLRL\n" +
        "FFFBBFFRLR\n" +
        "BFBBFFFRLR\n" +
        "FFBBFBBLRR\n" +
        "FFBFBBBLLR\n" +
        "FFBBBBFLRR\n" +
        "FFBFBFFLLL\n" +
        "FFFBFFFLLL\n" +
        "FFBFBFFLRL\n" +
        "BFBFFFBLRL\n" +
        "FBFFFFFLRR\n" +
        "BFBBBBFRRR\n" +
        "FBBFBBFLLL\n" +
        "FFFBBFFLLR\n" +
        "FFBFBBBLLL\n" +
        "BBFFBFFLLL\n" +
        "FBFFBFBRLR\n" +
        "BFBBBBFLRR\n" +
        "FBBBFBFRRL\n" +
        "BFFBBBBRRL\n" +
        "BFBBFFFLLL\n" +
        "BFBBFBFRRR\n" +
        "BFFBFBBLLL\n" +
        "FBBBBBFRRL\n" +
        "FFFBFBFRRL\n" +
        "FFBBBBFLLL\n" +
        "FBBFBBBLLL\n" +
        "FBFFBFFLLR\n" +
        "BFBBBBBLRR\n" +
        "FBFFFFFLLL\n" +
        "BFFFBBBRRL\n" +
        "FBFFFBBRLL\n" +
        "BFBBFBBLRR\n" +
        "FBBBFBBRLR\n" +
        "BBFFBFBLLR\n" +
        "BBFFFFBRLL\n" +
        "BFBBFBFLLR\n" +
        "FBBFFBFLRL\n" +
        "BBFFFBFRRL\n" +
        "BFFFBBBLRL\n" +
        "FBBBBFBRRL\n" +
        "BFBFBFBRRL\n" +
        "FFBFFBBRRR\n" +
        "FBBFFBBLLL\n" +
        "BFFBFFFRLL\n" +
        "FFFFBFFRLR\n" +
        "FFBFFBBRLL\n" +
        "FBBBFFFLRL\n" +
        "FFBFBFBRRL\n" +
        "BFBBBFFLLL\n" +
        "FBBBBFBLLL\n" +
        "FFFBBBBLRR\n" +
        "FBFFFFBRLR\n" +
        "FFBBBBFLRL\n" +
        "BFBBBBFRRL\n" +
        "FFFFBBFLLL\n" +
        "BFFFBBBLLR\n" +
        "FFFBBBBRRL\n" +
        "FBBBFBFLLL\n" +
        "BFFFFFBLRL\n" +
        "FFFBFBBRRL\n" +
        "BFFBBFBRLL\n" +
        "FBFBBFBLRR\n" +
        "FBBBFFFLLL\n" +
        "BFBFFFFRRL\n" +
        "FBBBBFFRLL\n" +
        "BFBFFBBLRL\n" +
        "FBBBBFBRLL\n" +
        "FBBFFBBRLR\n" +
        "FFBBBFBRRL\n" +
        "FFFBBFFLRL\n" +
        "BFBBFBFRLL\n" +
        "FBBFBBFRLL\n" +
        "FBFBBBFLLR\n" +
        "FBFFBFBRLL\n" +
        "BFFFBFFRRR\n" +
        "BFBFBBFLRL\n" +
        "FBBBBBFLRR\n" +
        "FFFFBBFRRL\n" +
        "BFBBFFBRRR\n" +
        "FBBFFFBLRR\n" +
        "BFBBBFBLLR\n" +
        "FBBBBFBRLR\n" +
        "BFBFFFFRLL\n" +
        "FFFBBBFLLL\n" +
        "BFFFBFFLLL\n" +
        "FBFBFFBRLL\n" +
        "BBFFFFFLLL\n" +
        "FFFFFBBLRR\n" +
        "BFFFFFFLRR\n" +
        "BFFBFBFLRR\n" +
        "FFFBFFBLLR\n" +
        "BFFFFFFLLR\n" +
        "FBFFBBBRRR\n" +
        "FFFFBFBLLR\n" +
        "BFFBBFFLLL\n" +
        "FFFFFBBLLR\n" +
        "BFBBBFBRRL\n" +
        "FBFFBBBRLR\n" +
        "BBFFFFBLRL\n" +
        "FFBFFBFLLL\n" +
        "FBFFFFBLRR\n" +
        "FFFBFBFLLR\n" +
        "FFBFFFFLLR\n" +
        "FFFFFBFLRL\n" +
        "BBFFFBBLLL\n" +
        "BFFBFBFRRR\n" +
        "FBBBFFFLLR\n" +
        "BFBBBFBLLL\n" +
        "FBFFFFFRRR\n" +
        "FBFFBBFLRL\n" +
        "BFFBBFBLLR\n" +
        "FBBFFBFRLR\n" +
        "FFFFFBFRRL\n" +
        "FFBFFBBLLL\n" +
        "BFBFFBFRLL\n" +
        "BFBBFFFRLL\n" +
        "FBBBFBFRLL\n" +
        "FBFBFFFLLL\n" +
        "BBFFFBBLRR\n" +
        "FFFBFBFLLL\n" +
        "BBFFBFBLRR\n" +
        "FFBBFBFLRR\n" +
        "BFFBBFFRLR\n" +
        "FBFBFBBRLR\n" +
        "FBBFFBBRRR\n" +
        "FFBFFFBRRR\n" +
        "BFBBFBBLRL\n" +
        "FFFBFFFRLL\n" +
        "BFBBFBFLRL\n" +
        "BFBFBBBLLL\n" +
        "FBFBBFFLRL\n" +
        "FFBFBBBRRL\n" +
        "FFFBFFBRRL\n" +
        "FFBFFFFRLR\n" +
        "FFFFBBBRRR\n" +
        "FFFFBFBLLL\n" +
        "FFBFFBFRRR\n" +
        "FFBFFBFLRR\n" +
        "FFFBBFFRLL\n" +
        "FBBBFFFRLR\n" +
        "FFBFFFBRLL\n" +
        "FBBBFBFRRR\n" +
        "FBFFFBFLRR\n" +
        "FBBBFBFLRL\n" +
        "FBFBFFFRRL\n" +
        "BFBFFFFLRL\n" +
        "FFBBFFBLRL\n" +
        "BBFFBFBLLL\n" +
        "FBFBBBBRRR\n" +
        "FBBFFFBLLR\n" +
        "FBBFBFFRRL\n" +
        "FFBFBFBLLR\n" +
        "BFFBBBFLRR\n" +
        "FBFBFFBLRL\n" +
        "FBFFBBBLLL\n" +
        "FFBFBBFRRL\n" +
        "BFFBFFFLLR\n" +
        "FBBBFBBLRL\n" +
        "BFFBBFBRLR\n" +
        "BFFFBFBRLL\n" +
        "BFFFFBBRRR\n" +
        "FBFFBBFLLR\n" +
        "FFBFFFBRRL\n" +
        "FFBBBBBRRL\n" +
        "BFFBBBBRLR\n" +
        "BFFFBFBRLR\n" +
        "FBBBBBBLLL\n" +
        "BFFFBFBRRR\n" +
        "FFBBBFFRLR\n" +
        "FBBBFBFLLR\n" +
        "FBFBFBFRRR\n" +
        "FBFBBBBLLL\n" +
        "BFBFBFBRLR\n" +
        "FFFFBFFLRR\n" +
        "BFFBFBBRLL\n" +
        "BFBFFFBLLR\n" +
        "BFBBFBBLLL\n" +
        "FBFFBBBLLR\n" +
        "FBBFBBFRRR\n" +
        "FFFBFFFLLR\n" +
        "FFFBFBBRLL\n" +
        "BFBFFBFLLR\n" +
        "BFFFFBBLRL\n" +
        "FBFBBFBLLL\n" +
        "FBBFFBFRLL\n" +
        "BFBBBBFRLR\n" +
        "BFBFFFBRLL\n" +
        "BBFFFBFRLR\n" +
        "FFFFBBBLRL\n" +
        "BFBBFFBLRL\n" +
        "BBFFBBFRRL\n" +
        "FFBBBFBLLL\n" +
        "FBFBFBFLRL\n" +
        "FBBBBBBRRL\n" +
        "FFFFFBBRRR\n" +
        "FFFFFBFRRR\n" +
        "FBFFFBBRRR\n" +
        "BFFBBFBRRL\n" +
        "BBFFFFFRLL\n" +
        "FFFBFFBRLR\n" +
        "FFBBFFFRRL\n" +
        "FBFBFFFRLR\n" +
        "BFFBBBFRLR\n" +
        "BFBBBBFLRL\n" +
        "FBFFBFBRRL\n" +
        "FFBFBBBRRR\n" +
        "FFFFBBFRLL\n" +
        "FFFFBBBRLL\n" +
        "FBBFFFBLLL\n" +
        "BFBBFBBRRR\n" +
        "BFFBBBFRLL\n" +
        "BFFFBFFRLR\n" +
        "FBFBFFBLLL\n" +
        "BFFFFBBRLL\n" +
        "BBFFBFFLRL\n" +
        "BFBBBBBLRL\n" +
        "BFFFFBBRRL\n" +
        "BFFBFFFLRL\n" +
        "BBFFBBFRLR\n" +
        "BFBBFBFLLL\n" +
        "BBFFBFFRLR\n" +
        "FBBFBBBRLL\n" +
        "FFFBFBFLRR\n" +
        "BFBFFBFLLL\n" +
        "FFFFBBFLRR\n" +
        "FFFBBBBLLL\n" +
        "BFBFFFFRRR\n" +
        "FBFBBBFRLL\n" +
        "FFBBFFFLRR\n" +
        "FBFBBBFRLR\n" +
        "BFFFBBFLLR\n" +
        "BFBBBBBLLR\n" +
        "BFFBFFBRRR\n" +
        "FBBBFFBRLR\n" +
        "BFBFBBFLLL\n" +
        "FBFFFFFRLR\n" +
        "BFFFFFFLLL\n" +
        "BFFBFFBRLR\n" +
        "BBFFFFBRLR\n" +
        "BBFFBFBRLR\n" +
        "FBFBFBBLRR\n" +
        "BFFFBBFLRR\n" +
        "FBFFBBBRLL\n" +
        "FFFFBBFLRL\n" +
        "FFBFFBBLRL\n" +
        "FBFFBBFLLL\n" +
        "FBFBBFFLLL\n" +
        "FFBBFFBRLR\n" +
        "BFFFBBBRRR\n" +
        "BBFFFBBLLR\n" +
        "BFFBBBFLRL\n" +
        "BBFFFBBRLR\n" +
        "FBBBBBBLLR\n" +
        "FBFBBFFRRR\n" +
        "FBFFBBFRLL\n" +
        "FFFBBFBRLL\n" +
        "FFFBFBBRLR\n" +
        "FBFFBFFLLL\n" +
        "FFBBBBBLRR\n" +
        "FBFFFFFLLR\n" +
        "FBFFFBBLRL\n" +
        "FBFFBFBLRR\n" +
        "FFBBBBFRRR\n" +
        "FBBBFFFRRL\n" +
        "FFFFBBFLLR\n" +
        "FFFFFBFLRR\n" +
        "BBFFBBFLLL\n" +
        "FBFBFBBLLL\n" +
        "FBFBFFBRRR\n" +
        "FBFFBFFLRR\n" +
        "FBBFFFFLRR\n" +
        "FBBFBFFLLR\n" +
        "BFFBBBFRRR\n" +
        "FFBBBBBRRR\n" +
        "BFFFFFBRLR\n" +
        "BFFBFBFRLR\n" +
        "FFFFBFFRLL\n" +
        "BFBFFBBRLR\n" +
        "BFBBFFFLRL\n" +
        "FBFFFFBLLR\n" +
        "FFBFFBFRLL\n" +
        "BBFFFBBLRL\n" +
        "FBBFFBFLRR\n" +
        "BFFFFBBRLR\n" +
        "BFBBFBBRRL\n" +
        "FBBFBFBRRR\n" +
        "BFFFBFFLRL\n" +
        "FFBBFBBRRL\n" +
        "FFFBFFBLRR\n" +
        "FBBFBFBRRL\n" +
        "BFBFBBFLLR\n" +
        "BBFFFBBRRL\n" +
        "FFBFBBFLRL\n" +
        "FFBFFFBLRR\n" +
        "FBFFBFBLLR\n" +
        "BFBFFBBRRL\n" +
        "BFFBFFFLRR\n" +
        "BFBBBFBRRR\n" +
        "FFBFBBBLRR\n" +
        "BFFFFFBRRL\n" +
        "BFBFBFFRRL\n" +
        "FFBFFBBRRL\n" +
        "FBBBBFBLRL\n" +
        "BFBFFFFRLR\n" +
        "FBBBFFFRRR\n" +
        "BBFFBBFLRR\n" +
        "FFBFBFBRLR\n" +
        "FBBBFBBLRR\n" +
        "FFBFBBBRLL\n" +
        "BFFBBFFRRL\n" +
        "BBFFBFBRLL\n" +
        "FBBBFBBRRR\n" +
        "FBFFFFFLRL\n" +
        "FFBBFFBLLR\n" +
        "FBBFBBBRRL\n" +
        "FFFFBBBRLR\n" +
        "FBBFBBBRLR\n" +
        "FBBBBFBLLR\n" +
        "FFBFBFBLLL\n" +
        "BFFFBBFRRL\n" +
        "FBFFFBFRRL\n" +
        "BFBFBBBRRR\n" +
        "FBFBFBBLRL\n" +
        "BFBFBFFRRR\n" +
        "FFBBBBBRLL\n" +
        "FFFBBBFRRL\n" +
        "FFBBFFBLRR\n" +
        "BFBBBFBLRR\n" +
        "FBBBBBBLRR\n" +
        "FBFFFBBLLR\n" +
        "FBBFBFFLRL\n" +
        "FFBBBFFLRL\n" +
        "FFBFFBFLLR\n" +
        "FFFBBFFRRL\n" +
        "FFFFBFBRRL\n" +
        "FBFBBFBRRL\n" +
        "BFBBFFBLLL\n" +
        "BFFBFBBRRL\n" +
        "FFFFBBBRRL\n" +
        "BBFFFFFRRL\n" +
        "BFFBFFBRRL\n" +
        "FFFBBBFRLL\n" +
        "FFBFBBFRLR\n" +
        "BBFFFBFRLL\n" +
        "BFBBFBBRLL\n" +
        "FFFBFBBRRR\n" +
        "FBBFFFBRRL\n" +
        "FBFBFBFRLL\n" +
        "FBBFFFFRRR\n" +
        "BFBFFBFRRL\n" +
        "FBBBFBFLRR\n" +
        "FFBFBFBLRL\n" +
        "FFBBBBFLLR\n" +
        "FFFFFBFLLR\n" +
        "FFBFFFBLLL\n" +
        "BBFFBFFRLL\n" +
        "FFFBBBBRRR\n" +
        "FFBFFBBLRR\n" +
        "BFFFFFFLRL\n" +
        "FFFBBBFLRL\n" +
        "FBFFFBFLLR\n" +
        "BBFFFBFLRR\n" +
        "BFBFFFBRLR\n" +
        "BFFFBBFRLR\n" +
        "BFBFBBFRRL\n" +
        "BFBFFBBRRR\n" +
        "FFBFBBFLLL\n" +
        "FFFBBFBLLL\n" +
        "FFBBFFBRRL\n" +
        "FBFBBBFLLL\n" +
        "BFFFFFFRLR\n" +
        "BBFFFBFLLR\n" +
        "FBBFBFFRLL\n" +
        "FBFBFFBLRR\n" +
        "FBBFBFBRLR\n" +
        "FBFFBBBRRL\n" +
        "BFFBBFFRLL\n" +
        "BFFBFFBLLL\n" +
        "BFBBFBFRRL\n" +
        "FFFBFBFLRL\n" +
        "FFBBFBBRLR\n" +
        "FBBBBBFLRL\n" +
        "BBFFBFBRRL\n" +
        "FFFFBFBLRR\n" +
        "FFBFBFFRRL\n" +
        "FBFBBBBLRR\n" +
        "FFFFBFFRRR\n" +
        "BBFFBBFLRL\n" +
        "BFBBBBFLLL\n" +
        "FBBFBFBLRR\n" +
        "FBBBBBBRLL\n" +
        "FFFBBBBRLR\n" +
        "BBFFFFFRLR\n" +
        "FBFFFFFRLL\n" +
        "BFBBFFBLLR\n" +
        "BFFFFBFRLR\n" +
        "FFBBBFFRRL\n" +
        "FFBBBFFRLL\n" +
        "BFFBBFBLLL\n" +
        "FFFBBBFRRR\n" +
        "BFFFFFBRRR\n" +
        "FBFFFBFRLL\n" +
        "FBBFBFFLRR\n" +
        "BFFFFFBLRR\n" +
        "BFBFBFBLRL\n" +
        "BFBBBFFLRL\n" +
        "FFBFFFFRLL\n" +
        "FBFBFBFRLR\n" +
        "BFFFBBFRLL\n" +
        "FFBBFBFRLR\n" +
        "FBFBBFBLLR\n" +
        "FBFFBFFRRL\n" +
        "FBBBBFFLRR\n" +
        "BFBFBBBRLR\n" +
        "BFBBBFFRRL\n" +
        "FFFBFBBLRL\n" +
        "FBBBFFBLRR\n" +
        "BFBFFBFLRL\n" +
        "BFFFFFBRLL\n" +
        "BFFFBFFLLR\n" +
        "BFBBBFBRLR\n" +
        "FFFBFFFLRR\n" +
        "FBFBFBFRRL\n" +
        "FBFBFFFLRL\n" +
        "FBBFBBBLLR\n" +
        "BFBFFFFLLR\n" +
        "FBFFFBFLLL\n" +
        "FBBFBBFRLR\n" +
        "FBBFFFBRLL\n" +
        "FFFBFFBLRL\n" +
        "FBFBBFBRLR\n" +
        "BFBBFFFRRR\n" +
        "BFBFBFFRLL\n" +
        "FBFBFBBRRL\n" +
        "FFFBFBFRLL\n" +
        "FBBFFBBRLL\n" +
        "BFFBFBFLRL\n" +
        "BFFFFBBLLR\n" +
        "BFFFFFFRRR\n" +
        "BFBBBFBLRL\n" +
        "FFFBBFFLLL\n" +
        "FBBBFBBRLL\n" +
        "FFFBFFBLLL\n" +
        "FBFFFBFRRR\n" +
        "BFBFFBFLRR\n" +
        "FFBFFFFLRR\n" +
        "BFBBBFFRLR\n" +
        "FBFBFFBLLR\n" +
        "FFBFBBFRRR\n" +
        "FFBBFFBLLL\n" +
        "FFBFFFFLLL\n" +
        "BFFBBFBRRR\n" +
        "FFFBBBFLRR\n" +
        "FFBBFFBRLL\n" +
        "FFBBFBBLLL\n" +
        "BFFFFBFLLL\n" +
        "FFFBBFBRRR\n" +
        "FFBFFFFRRL\n" +
        "FFFBBFBRRL\n" +
        "BFFBBBFRRL\n" +
        "FBBBFFBRLL\n" +
        "FBFBFBBLLR\n" +
        "FBBBFBBRRL\n" +
        "BFBFBBBRRL\n" +
        "BFBFBFFLRR\n" +
        "BFFFFFBLLL\n" +
        "BFBFBBFRLL\n" +
        "FBBBBBFRLL\n" +
        "BFFFBFBLRL\n" +
        "FBFBBBBRLR\n" +
        "FBFFFBFLRL\n" +
        "FFBFBFFRRR\n" +
        "BFBFBFBLLL\n" +
        "BFBBFFBRLL\n" +
        "FBBBBBBLRL\n" +
        "BFFFBBFLLL\n" +
        "FBBFBBFLRL\n" +
        "FFFFBBFRLR\n" +
        "BFBFFFBRRR\n" +
        "FFBFBFFLRR\n" +
        "FFFFFBFLLL\n" +
        "FBFBFFFRRR\n" +
        "FBFFFBFRLR\n" +
        "FBFBBFBRLL\n" +
        "BFBFFBFRRR\n" +
        "BFBBFFBRLR\n" +
        "FBBBBFFRRL\n" +
        "BFBFFFFLLL\n" +
        "BFBFFFBLRR\n" +
        "FBFBBBBRRL\n" +
        "BFFFBFBLRR\n" +
        "FFBBFBFLLR\n" +
        "FBBBFFBRRL\n" +
        "FFFFFBFRLR\n" +
        "FFFBBFBLLR\n" +
        "FBFFBFFLRL\n" +
        "FFFBFBFRRR\n" +
        "BBFFBFBRRR\n" +
        "BFBBBBFLLR\n" +
        "BFBBBBBRLR\n" +
        "FFBBFFFLRL\n" +
        "FBBBFFBLLR\n" +
        "BFBFBFBLRR\n" +
        "FFBFBFFLLR\n" +
        "FBFFBFFRLL\n" +
        "FFBFFFBLLR\n" +
        "BFBBFBFRLR\n" +
        "FBBBFBBLLL\n" +
        "BFBBBBBRLL\n" +
        "FBFBFFBRLR\n" +
        "FFBBBFBLRR\n" +
        "FBBFFBFLLR\n" +
        "FFFBBFBLRL\n" +
        "FBFBBBFLRR\n" +
        "FBBBFFFLRR\n" +
        "FBFFFFBRRR\n" +
        "FFFFFBBLRL\n" +
        "FFBBBBFRLR\n" +
        "BFFBFBFRLL\n" +
        "BFFFFBFRLL\n" +
        "BFFFBFBLLL\n" +
        "BFBBBFBRLL\n" +
        "FFFBFFFRLR\n" +
        "FBBBFFBLLL\n" +
        "FBFBBFFLRR\n" +
        "FFFBFBBLRR\n" +
        "BFBFFFBRRL\n" +
        "FFBBBFFRRR\n" +
        "FBFFFFBRLL\n" +
        "FFFBBFBLRR\n" +
        "FFFFFFBRLR\n" +
        "FFFBBBBLLR\n" +
        "FFFBFFFRRL\n" +
        "FBBFFBBRRL\n" +
        "FBBBBFBLRR\n" +
        "FBFFBFBLLL\n" +
        "FFBFFFBRLR\n" +
        "BFFBBBFLLR\n" +
        "FFFBBBBRLL\n" +
        "FFFFBBBLRR\n" +
        "FFFBBFFLRR\n" +
        "BBFFFFFLLR\n" +
        "FFFFBFBLRL\n" +
        "BFBFBBBLRR\n" +
        "FBBFFFBRLR\n" +
        "FBFFFBBRLR\n" +
        "FBFFBBFLRR\n" +
        "BFBBFBFLRR\n" +
        "FBFBFFFRLL\n" +
        "BBFFBFFRRR\n" +
        "BFFBBBBRLL\n" +
        "BFBBFFBRRL\n" +
        "BFFBBFFLLR\n" +
        "BFBFBBFRRR\n" +
        "FBFBFBFLLL\n" +
        "FBBBFFFRLL\n" +
        "FFBBFBBRRR\n" +
        "FFBBBFFLLL\n" +
        "BFFBFFFLLL\n" +
        "BFBFFBBLRR\n" +
        "FFFFBFBRLR\n" +
        "FBFBBBFRRL\n" +
        "FFFFBBBLLL\n" +
        "FBBBBBFLLR\n" +
        "BFBFBBBLRL\n" +
        "BBFFFFFLRR\n" +
        "BFFBFFBLLR\n" +
        "BFBBFFBLRR\n" +
        "FBBBFBBLLR\n" +
        "FFBFBBFLRR\n" +
        "FBFBFBFLLR\n" +
        "FBFBFBBRRR\n" +
        "BFFFFBFLRL\n" +
        "FFFBFFFLRL\n" +
        "BBFFFBBRRR\n" +
        "BFBBFFFLRR\n" +
        "FFFFBFFLRL\n" +
        "BFFBBFFRRR\n" +
        "BFFBFBBRLR\n" +
        "FFBBBFBRRR\n" +
        "FFBBFBFRRL\n" +
        "FBBFFBFRRL\n" +
        "FBBFBBFRRL\n" +
        "FBBFBFBLLL\n" +
        "BFBBBBBRRL\n" +
        "FFBBFFFLLR\n" +
        "FFBBBFBLRL\n" +
        "FFBBFFFRLR\n" +
        "BFBBFBBLLR\n" +
        "FFBFFBFRRL\n" +
        "FBBBBFFLLL\n" +
        "BFFFFBFLRR\n" +
        "BFBBBFFRLL\n" +
        "BFBBBBBRRR\n" +
        "BBFFFFBLLL\n" +
        "FBFFFBBLRR\n" +
        "FBBBBFFRLR\n" +
        "FBBFBFFRLR\n" +
        "FBFBBFFRRL\n" +
        "FBFFFFBRRL"}.b

function main(){
    const lines = INPUT.split("\n").map(function (line){
        let [a,b] = line.split(/(?<=[FB])(?=[RL])/)
        return {row:parseInt(a.replaceAll('F', 0).replaceAll('B',1), 2),
        col:parseInt(b.replaceAll('L',0).replaceAll('R',1),2)
        }
    });
    console.log(lines);
}

module.exports = main;
if (require.main === module) {
    console.log(main())
}