const INPUT = {b:"qpicundo\n" +
        "fiqcdbkyuoz\n" +
        "\n" +
        "rahgpijvyfd\n" +
        "biwvrajyp\n" +
        "ajbrvopeiyw\n" +
        "\n" +
        "cv\n" +
        "v\n" +
        "qwvo\n" +
        "v\n" +
        "\n" +
        "ftsvmcrbxn\n" +
        "zkvdfsjxrablnpoutg\n" +
        "nbxferitsv\n" +
        "nvfhytbrwxs\n" +
        "\n" +
        "hdamqjxnipezgrwutc\n" +
        "vmszeqacbiuwpokxn\n" +
        "\n" +
        "kushbeg\n" +
        "fjarlmdhvspkbie\n" +
        "cesznhbxkg\n" +
        "buekysxh\n" +
        "zbkhse\n" +
        "\n" +
        "hrxgtupf\n" +
        "gmhfxutje\n" +
        "\n" +
        "cnajtoldrhkmiqx\n" +
        "onmqriltahxjkcd\n" +
        "jqimcxkrdoanhlt\n" +
        "\n" +
        "fhbtngdzq\n" +
        "ndbghqftz\n" +
        "qfhdgtznb\n" +
        "nbdgtfhzq\n" +
        "\n" +
        "dxeoijmbprfaug\n" +
        "ohspnculriwexbk\n" +
        "zuviobjraeqxgp\n" +
        "\n" +
        "oitgeazcqrkyvmphl\n" +
        "bapolshcnvekdyrijz\n" +
        "\n" +
        "hxaiwmzpglyrunqkdfvjbsc\n" +
        "jsymwqnfzhbvrdxcupglika\n" +
        "bqzsuwpkfjxnildehagvyrmc\n" +
        "\n" +
        "agkfyuvncr\n" +
        "kvucyrfgan\n" +
        "cankyfurgv\n" +
        "\n" +
        "qrikblojp\n" +
        "wtvfscqiyh\n" +
        "cfwynimq\n" +
        "wuqxmegszi\n" +
        "\n" +
        "egvjnhmwuszotipdc\n" +
        "nzgvmjshpcuetiwod\n" +
        "dqwpiyzmcaoxuhetvngs\n" +
        "\n" +
        "xae\n" +
        "xaet\n" +
        "xea\n" +
        "xae\n" +
        "exa\n" +
        "\n" +
        "jizaflhpxdwumgs\n" +
        "duaflpzwxmsgjhi\n" +
        "wfsmilagxhdzujp\n" +
        "\n" +
        "ijeyq\n" +
        "ezqji\n" +
        "zqeboij\n" +
        "qeijb\n" +
        "\n" +
        "bad\n" +
        "dba\n" +
        "debta\n" +
        "\n" +
        "h\n" +
        "x\n" +
        "x\n" +
        "x\n" +
        "\n" +
        "ulfkv\n" +
        "kuly\n" +
        "kuly\n" +
        "kjul\n" +
        "klu\n" +
        "\n" +
        "gpr\n" +
        "tkr\n" +
        "rd\n" +
        "r\n" +
        "dr\n" +
        "\n" +
        "mlcybiwua\n" +
        "owg\n" +
        "\n" +
        "cokrh\n" +
        "bomzakugxtwveiyn\n" +
        "osklqp\n" +
        "ofkq\n" +
        "cpqohk\n" +
        "\n" +
        "hcmyonbsarvldkgfpw\n" +
        "eslkdgounrvbfmywh\n" +
        "slkdhzvbfnymorgw\n" +
        "\n" +
        "efvugtbyzmdh\n" +
        "fumqpbvyej\n" +
        "ypcmbivuesf\n" +
        "\n" +
        "mdgfxrjycuwepi\n" +
        "sdtmejcyubgqlox\n" +
        "xdmyecujkgzafr\n" +
        "\n" +
        "arhevtgdomli\n" +
        "idvraethmglo\n" +
        "ehivtolgrpwa\n" +
        "\n" +
        "zrjkgal\n" +
        "rcjga\n" +
        "rljgasp\n" +
        "wrbhjnav\n" +
        "jslra\n" +
        "\n" +
        "go\n" +
        "goxw\n" +
        "\n" +
        "nfycq\n" +
        "fnyc\n" +
        "\n" +
        "m\n" +
        "kf\n" +
        "j\n" +
        "d\n" +
        "q\n" +
        "\n" +
        "wcx\n" +
        "xfcqw\n" +
        "qxwtu\n" +
        "oxkpiyg\n" +
        "\n" +
        "ud\n" +
        "qr\n" +
        "somtbxcv\n" +
        "diae\n" +
        "ij\n" +
        "\n" +
        "vftcjdgs\n" +
        "cdtvfgsj\n" +
        "gvfsdcjt\n" +
        "vgfksjdct\n" +
        "gtefcdjvms\n" +
        "\n" +
        "khgdmzlcae\n" +
        "zedcslqka\n" +
        "tfdckeaxmzlhr\n" +
        "aezkdrlcs\n" +
        "wycukdlvaezb\n" +
        "\n" +
        "hzakytmxgcqvunsbjoidwe\n" +
        "touhjicbexangskvzdwmq\n" +
        "ubdepshljqaivfnzgxwromctk\n" +
        "\n" +
        "hxgcwlvzujrsbe\n" +
        "zxceuhvwgrnldbsjm\n" +
        "rvczewuhsxjlgb\n" +
        "\n" +
        "rhiuambjzqn\n" +
        "imqzjpburanh\n" +
        "brmziaqujnh\n" +
        "aqifozjubhrnm\n" +
        "\n" +
        "ukrpajtcnlvysdhwf\n" +
        "rnytlpwaicjusd\n" +
        "ljyarntxhsbwucpd\n" +
        "lrjwscyvdntuap\n" +
        "\n" +
        "xwgtyqkf\n" +
        "wvuinb\n" +
        "zlmewri\n" +
        "\n" +
        "vajupxzg\n" +
        "bpzaux\n" +
        "pxzua\n" +
        "zpuax\n" +
        "\n" +
        "wmqd\n" +
        "dqmw\n" +
        "gdqwm\n" +
        "wqmd\n" +
        "umqrdw\n" +
        "\n" +
        "wrfhtn\n" +
        "rofwht\n" +
        "pwsrthf\n" +
        "\n" +
        "manfclbyrdxjik\n" +
        "bxflmyadknjcir\n" +
        "\n" +
        "sduzqohjtnkmi\n" +
        "hjtnyimzqdsuk\n" +
        "mjquhntdiksz\n" +
        "\n" +
        "ofr\n" +
        "qrl\n" +
        "\n" +
        "yhjzgdmslpn\n" +
        "zygdpjlmsn\n" +
        "\n" +
        "ailyqtfmzsopr\n" +
        "iazfmqslyrjhpt\n" +
        "tlpvqgaiuzsnmwfbeyx\n" +
        "dclofymkatspizhq\n" +
        "\n" +
        "clypfnqvimtuxwab\n" +
        "msogekqrzhjf\n" +
        "\n" +
        "hnvgmwrfj\n" +
        "rhfjgmw\n" +
        "igdfsrhj\n" +
        "hjfewlrg\n" +
        "\n" +
        "julft\n" +
        "fuijtqyc\n" +
        "owfjskvtg\n" +
        "ituejqfc\n" +
        "yuztqfdcirj\n" +
        "\n" +
        "rubfcosnikjzmyav\n" +
        "fymjibrucozavkns\n" +
        "uzanfkocrsyjbiv\n" +
        "yrbvncsjuoamkzfi\n" +
        "sfcjvyaqodezubnipkr\n" +
        "\n" +
        "qkgwlfhdy\n" +
        "nbjkrsveifz\n" +
        "foypxtcak\n" +
        "\n" +
        "cjqwymzgbxilsednupfovk\n" +
        "fgqevluowysidbnmxjkzp\n" +
        "liekuxymdsvbzqjnofwgtp\n" +
        "\n" +
        "sgfnmoljbdihqaeyuwcx\n" +
        "ojuwiqhdlnzfcsegxymab\n" +
        "wbftqhedrmikaluxsgpjncov\n" +
        "\n" +
        "paxhq\n" +
        "cos\n" +
        "fdb\n" +
        "\n" +
        "ognxqwer\n" +
        "qwgoxenr\n" +
        "gwqroxen\n" +
        "\n" +
        "fsdgo\n" +
        "kdocfslx\n" +
        "osbdif\n" +
        "hosdprf\n" +
        "gsvofzd\n" +
        "\n" +
        "oamvucfhpq\n" +
        "hquvglbsw\n" +
        "qrvhu\n" +
        "uvjhbltdq\n" +
        "\n" +
        "jfltodbmwxpcai\n" +
        "dwfihozpbcatljxm\n" +
        "pbwotmcldjxaif\n" +
        "txkbipfwdjmlcao\n" +
        "ajfmdxlipbtocws\n" +
        "\n" +
        "lkbehfsx\n" +
        "hxlksfebp\n" +
        "\n" +
        "lm\n" +
        "whnogp\n" +
        "kicyqtudszf\n" +
        "jn\n" +
        "\n" +
        "gcsewnmqdthv\n" +
        "gsbucadrmz\n" +
        "rocjzgsldm\n" +
        "\n" +
        "uprsfb\n" +
        "gfqnmlbjtev\n" +
        "fhwb\n" +
        "\n" +
        "awpv\n" +
        "a\n" +
        "a\n" +
        "\n" +
        "t\n" +
        "rtn\n" +
        "t\n" +
        "\n" +
        "yrfmxdnkel\n" +
        "lmdzewkxnr\n" +
        "drempnxkl\n" +
        "\n" +
        "kyh\n" +
        "yfh\n" +
        "kyh\n" +
        "yhk\n" +
        "\n" +
        "ybqx\n" +
        "xbyq\n" +
        "xnbqoyi\n" +
        "\n" +
        "rkelsyhwmjqoaxgbndzicu\n" +
        "swlgkjmbqhacioedvnur\n" +
        "dqorcpgjmhieunklwabs\n" +
        "uoijceghaqxlbnrwskdm\n" +
        "\n" +
        "xmd\n" +
        "mxd\n" +
        "xdm\n" +
        "xmd\n" +
        "\n" +
        "unjqpocarmtgfikxzsdhwlyebv\n" +
        "gwklmrhxdvpfbzyacueitqnso\n" +
        "\n" +
        "wfhlcpe\n" +
        "fqechzwal\n" +
        "hlwfec\n" +
        "ywbefclh\n" +
        "hecwlf\n" +
        "\n" +
        "v\n" +
        "v\n" +
        "s\n" +
        "\n" +
        "gzhspvqbtiyl\n" +
        "ltqiyurkhb\n" +
        "tbhlyrqi\n" +
        "\n" +
        "hepdy\n" +
        "ydephi\n" +
        "edsrhpy\n" +
        "edyph\n" +
        "pyhde\n" +
        "\n" +
        "upcjxiwvqmhafetsronkbl\n" +
        "atflkcnqumpohixbzsrjwve\n" +
        "wlovimkcxftspajbquerhn\n" +
        "ikqrstefvolhdwcbmapjuxn\n" +
        "ipsecmgurbxqtonvwjfkhal\n" +
        "\n" +
        "nrhjbowi\n" +
        "wiornbhv\n" +
        "bnwhroil\n" +
        "\n" +
        "szfukhordxjb\n" +
        "rfbunjtdsk\n" +
        "ndbjrkufzhso\n" +
        "ukrjbndfs\n" +
        "eukgdjmrfsyb\n" +
        "\n" +
        "gbzd\n" +
        "vdz\n" +
        "\n" +
        "oqfzdjk\n" +
        "kedfj\n" +
        "buwinxdrjgyh\n" +
        "\n" +
        "gy\n" +
        "euy\n" +
        "ywz\n" +
        "yk\n" +
        "\n" +
        "qfglvert\n" +
        "eftjpsln\n" +
        "\n" +
        "ujqwnmhszxcopivfgbe\n" +
        "wgunfyqopmzesadcvxjbt\n" +
        "\n" +
        "baiykdzpg\n" +
        "payezibmdgk\n" +
        "ikyzgpbda\n" +
        "pbdgakziy\n" +
        "pkdbazigy\n" +
        "\n" +
        "pojhgwqdycz\n" +
        "yldpsuwco\n" +
        "\n" +
        "lqiox\n" +
        "khglw\n" +
        "\n" +
        "iknzjfuqcx\n" +
        "qnkcovzui\n" +
        "zpnrqauywtdlme\n" +
        "gqunsfvzo\n" +
        "\n" +
        "ayhdk\n" +
        "ojybpl\n" +
        "yvpb\n" +
        "\n" +
        "ubmxehjto\n" +
        "xbtmoujeh\n" +
        "xmoejubkt\n" +
        "juoetxbm\n" +
        "\n" +
        "kvcbe\n" +
        "eckbpv\n" +
        "wceqvkbm\n" +
        "\n" +
        "hdojvxsbaiy\n" +
        "elwbsq\n" +
        "\n" +
        "mrng\n" +
        "wlz\n" +
        "\n" +
        "pbiluamrejsownyfkgx\n" +
        "odbpxnuizywltqvcs\n" +
        "\n" +
        "yhgoj\n" +
        "inls\n" +
        "vqzmeawutpf\n" +
        "cdyjxr\n" +
        "\n" +
        "weviflqhaotpu\n" +
        "csybrknxgm\n" +
        "zjmdkr\n" +
        "\n" +
        "wnp\n" +
        "wpn\n" +
        "pwn\n" +
        "wpn\n" +
        "\n" +
        "trfmhxeociukg\n" +
        "ecioxufhrmtk\n" +
        "thfxmenokcuir\n" +
        "ikxehroumftc\n" +
        "\n" +
        "jgxzko\n" +
        "jizkl\n" +
        "xoukjzv\n" +
        "\n" +
        "rkwnxumvyigodejlfp\n" +
        "okerwlypnvxdi\n" +
        "qztwohyxkcenadvbpr\n" +
        "\n" +
        "xtisomdj\n" +
        "uncyzkoesravi\n" +
        "\n" +
        "yrplsicjnox\n" +
        "riopycxsjlun\n" +
        "olyjcpsixnr\n" +
        "nxiprjclytos\n" +
        "\n" +
        "lypqxvjrueastb\n" +
        "lvpruqbatyx\n" +
        "ynvurplqabtdx\n" +
        "\n" +
        "a\n" +
        "aq\n" +
        "w\n" +
        "uzb\n" +
        "\n" +
        "b\n" +
        "b\n" +
        "b\n" +
        "b\n" +
        "\n" +
        "bdhtie\n" +
        "bthedi\n" +
        "dihebt\n" +
        "bqihdet\n" +
        "dbethi\n" +
        "\n" +
        "bmcfdeuhykarnxq\n" +
        "buxaynpetdkhmifqg\n" +
        "yabdjmxqunkehof\n" +
        "\n" +
        "hbjle\n" +
        "pyr\n" +
        "\n" +
        "ga\n" +
        "ga\n" +
        "ag\n" +
        "\n" +
        "hit\n" +
        "eft\n" +
        "\n" +
        "bls\n" +
        "sl\n" +
        "ysl\n" +
        "bsl\n" +
        "\n" +
        "qjtvniz\n" +
        "jit\n" +
        "iyjt\n" +
        "tij\n" +
        "\n" +
        "cindevpkljyarzqwh\n" +
        "zgtdpmsxnofbyiru\n" +
        "\n" +
        "phismdwurq\n" +
        "ximrwtlyzqh\n" +
        "hfmjziqraw\n" +
        "\n" +
        "ay\n" +
        "ay\n" +
        "eya\n" +
        "ya\n" +
        "\n" +
        "elnvry\n" +
        "ckiyeqnvml\n" +
        "yvenlzrs\n" +
        "vzneyl\n" +
        "revluny\n" +
        "\n" +
        "jbqenozxgd\n" +
        "xdjqgnoezb\n" +
        "nxqgeozbjd\n" +
        "gzeqobndxj\n" +
        "bqdegnzoxj\n" +
        "\n" +
        "wfroqvpdjyu\n" +
        "jprvwouqfdy\n" +
        "voudwqypfjr\n" +
        "jwuqyfpdrov\n" +
        "pjdwovyufrq\n" +
        "\n" +
        "wpmbq\n" +
        "bqmpw\n" +
        "mphqwb\n" +
        "\n" +
        "q\n" +
        "q\n" +
        "q\n" +
        "e\n" +
        "q\n" +
        "\n" +
        "mpwuo\n" +
        "opbwa\n" +
        "owgp\n" +
        "\n" +
        "rbmveola\n" +
        "eoizbmv\n" +
        "lqbaormve\n" +
        "\n" +
        "enqk\n" +
        "kqn\n" +
        "knq\n" +
        "\n" +
        "fdoajsxqhlinrywbgu\n" +
        "hxnuolryqdajgbifs\n" +
        "oaduxbjnigqflrysh\n" +
        "\n" +
        "r\n" +
        "i\n" +
        "i\n" +
        "i\n" +
        "\n" +
        "dngie\n" +
        "igdne\n" +
        "djfrgiwenmk\n" +
        "gdnie\n" +
        "gidne\n" +
        "\n" +
        "ompatvbu\n" +
        "pkmuxavbt\n" +
        "szufycrimbapw\n" +
        "vbuapm\n" +
        "kabupm\n" +
        "\n" +
        "quonbdt\n" +
        "otuybq\n" +
        "botqu\n" +
        "uqotb\n" +
        "qubozt\n" +
        "\n" +
        "j\n" +
        "j\n" +
        "yj\n" +
        "j\n" +
        "\n" +
        "duqnjebpv\n" +
        "lquynhc\n" +
        "\n" +
        "hndkojuxyslvrm\n" +
        "ovmndkwyhxuisjlr\n" +
        "kjlyhsdguprvoxnm\n" +
        "lsomkhyrjdxunv\n" +
        "gudhsnlrjkxmvyo\n" +
        "\n" +
        "vtpamce\n" +
        "ovzaryjmetpc\n" +
        "ncavpt\n" +
        "tpcavy\n" +
        "bwptvxdqhaikufc\n" +
        "\n" +
        "o\n" +
        "o\n" +
        "o\n" +
        "o\n" +
        "\n" +
        "jqluihoeak\n" +
        "ikeujqoalh\n" +
        "joahkluqie\n" +
        "\n" +
        "fqrmvtxas\n" +
        "zoiwqlmt\n" +
        "xvqhgebtsm\n" +
        "tpmeq\n" +
        "\n" +
        "fkaeotvzuwyxdjs\n" +
        "xafmzeycqbshvdgkl\n" +
        "tyxasdvkefz\n" +
        "vxoaksyzfed\n" +
        "\n" +
        "rkfvodejlb\n" +
        "qahc\n" +
        "\n" +
        "urabynscomx\n" +
        "bvmaqynlecf\n" +
        "khjlyzcdigpbtanm\n" +
        "\n" +
        "losbxwmapcdrzfyj\n" +
        "ujmlczgbwxyehkoq\n" +
        "jcgqylwbmzxo\n" +
        "\n" +
        "g\n" +
        "g\n" +
        "\n" +
        "bvs\n" +
        "s\n" +
        "s\n" +
        "\n" +
        "bhjwfznyraolkce\n" +
        "fbqjlrcwaokte\n" +
        "bvlrwotfecdkja\n" +
        "rwkflbxijougmepac\n" +
        "kfwajczeoblrt\n" +
        "\n" +
        "lhdcfskwxaerjiotzvn\n" +
        "zaiefvhslwrcjoxk\n" +
        "zoxjibkalmshrevcup\n" +
        "\n" +
        "egvpws\n" +
        "epwgsv\n" +
        "vcpsgem\n" +
        "ozvyetksrxagqp\n" +
        "lpmgseuv\n" +
        "\n" +
        "oupbzjesrfwnvklxtiygdc\n" +
        "iyjudbvzegtscownlrkfp\n" +
        "gwfzvlynutkprosedbicj\n" +
        "wdkhujnigopzbcystelvrf\n" +
        "dgrlvbtfzinpkusjwceoy\n" +
        "\n" +
        "xupqorents\n" +
        "pensurtqxo\n" +
        "orensquxpt\n" +
        "prsuxonteq\n" +
        "snxqrpotue\n" +
        "\n" +
        "obryetcjszpnuwgxilkd\n" +
        "ropejxinuskybcgwltz\n" +
        "zuvrgmwftjnelqsxkpcyi\n" +
        "nxkzhlpgsdyrwejtciu\n" +
        "\n" +
        "yzriohapbgs\n" +
        "isprgzobahy\n" +
        "riyabgohszp\n" +
        "\n" +
        "lxczkmearuhnf\n" +
        "mxfnkczruhela\n" +
        "\n" +
        "krcoivbedawtzuhq\n" +
        "wnksyfjarde\n" +
        "\n" +
        "xsguj\n" +
        "usxjg\n" +
        "gsujx\n" +
        "gjxus\n" +
        "ugsjex\n" +
        "\n" +
        "hy\n" +
        "hsn\n" +
        "pz\n" +
        "c\n" +
        "n\n" +
        "\n" +
        "wdnzt\n" +
        "wqzrdkbc\n" +
        "nzwdtf\n" +
        "\n" +
        "h\n" +
        "mh\n" +
        "bh\n" +
        "\n" +
        "kqalzofbu\n" +
        "wyncpf\n" +
        "ixf\n" +
        "hf\n" +
        "\n" +
        "tihepcdnxg\n" +
        "scfhe\n" +
        "cefh\n" +
        "\n" +
        "zxlhgpuowimedyjktqrc\n" +
        "zgcirhetqjmlpdokuywx\n" +
        "oqykmcupwridlxhztjge\n" +
        "\n" +
        "xvstwya\n" +
        "vtywxas\n" +
        "yvxtaws\n" +
        "\n" +
        "gsnij\n" +
        "gpjshn\n" +
        "ogjsnlze\n" +
        "jzongs\n" +
        "swljegdn\n" +
        "\n" +
        "teaxnu\n" +
        "atreuxn\n" +
        "axlwtnu\n" +
        "pvukhadbjtxcn\n" +
        "\n" +
        "uvgz\n" +
        "zsm\n" +
        "\n" +
        "xrjduek\n" +
        "djuiker\n" +
        "\n" +
        "mgbsqftv\n" +
        "bgvsfmqt\n" +
        "ftsvmqgb\n" +
        "tvgfbmcqs\n" +
        "mbfsqvtg\n" +
        "\n" +
        "opjuwfskvclrxgtbnzemqhia\n" +
        "jsutkmcybpgowzaqxrnfhliev\n" +
        "wmhbsitkclvzfxgjpurneaqo\n" +
        "\n" +
        "xblyaorpvdjqfehuszi\n" +
        "pyihjwadusfqbv\n" +
        "\n" +
        "lhtxfsockq\n" +
        "hsoflktqcx\n" +
        "lkfhtxocsq\n" +
        "fqocxklhst\n" +
        "\n" +
        "zwt\n" +
        "zhtbw\n" +
        "wzitlb\n" +
        "wtbz\n" +
        "zqjtw\n" +
        "\n" +
        "pnowugqirtlmzadsv\n" +
        "uoqpznmldrtwjvsi\n" +
        "\n" +
        "meavkwnigcbjplhd\n" +
        "minwphevajckdtgl\n" +
        "\n" +
        "udqekwjaxm\n" +
        "xujwqmkead\n" +
        "emauxkdqwj\n" +
        "\n" +
        "sxtnmaechq\n" +
        "qnesxcth\n" +
        "ntkxshecq\n" +
        "\n" +
        "fl\n" +
        "yt\n" +
        "\n" +
        "pnjmvxgd\n" +
        "xeqdpmsvgnj\n" +
        "nvjpxmgd\n" +
        "pxngjvdm\n" +
        "\n" +
        "ezfswkgqrjnbmpvliycxua\n" +
        "ubzspxqgnejywkmirfv\n" +
        "pbigrvjshkxemnfuwyqz\n" +
        "\n" +
        "unc\n" +
        "cnua\n" +
        "rknluc\n" +
        "zebcntou\n" +
        "func\n" +
        "\n" +
        "ucbipqmenafw\n" +
        "cqiamwenufb\n" +
        "bqveahpzcuniwf\n" +
        "uatniwcdbqxjeyrof\n" +
        "faeincqbuw\n" +
        "\n" +
        "mkbtyagfurhszxcpqjweivld\n" +
        "zygiwpcnuxqjdlmvfeohsb\n" +
        "\n" +
        "qtczamlod\n" +
        "qovpdgfla\n" +
        "ldaqi\n" +
        "dwnarbsheyxl\n" +
        "atvuljqocdf\n" +
        "\n" +
        "cjxpytmesknol\n" +
        "esxcmpoyljtn\n" +
        "eosljxtcpknmy\n" +
        "ptsoyjmclbxnve\n" +
        "\n" +
        "gsmxqruzwhtb\n" +
        "gwrthqmisbv\n" +
        "tgbhqmrsw\n" +
        "sqwmgrhvtb\n" +
        "hqrbsmfwtg\n" +
        "\n" +
        "xdzjpkolmgchyatnbqv\n" +
        "yiuprfwxnosme\n" +
        "\n" +
        "aruewcdm\n" +
        "nroei\n" +
        "\n" +
        "yxh\n" +
        "xhy\n" +
        "hyqx\n" +
        "\n" +
        "a\n" +
        "a\n" +
        "a\n" +
        "a\n" +
        "a\n" +
        "\n" +
        "gkrsznedvcwxpymtu\n" +
        "irqenbkaox\n" +
        "\n" +
        "kajrbfgdlmenh\n" +
        "mflgandejrhkybx\n" +
        "afbmqelnjkhgrd\n" +
        "\n" +
        "vfmns\n" +
        "zonlxhfrvm\n" +
        "\n" +
        "zcjhsuikpbaqgwnxrvedmfyt\n" +
        "dvpnabeuwzqhrsgfyioxjtck\n" +
        "qjwdzgurbcsehtxvkfanyip\n" +
        "ajivfcuzwhrnptxyqbdskeg\n" +
        "xjwdfupbnzsqygheiarkvct\n" +
        "\n" +
        "s\n" +
        "b\n" +
        "i\n" +
        "b\n" +
        "\n" +
        "wqoxgkjatmlcynhs\n" +
        "mojxlyhcnatwsk\n" +
        "clktjowxayhsmn\n" +
        "sxonlyakmtjhcw\n" +
        "mawkojnhlystcx\n" +
        "\n" +
        "hovsj\n" +
        "ujvso\n" +
        "jsvo\n" +
        "\n" +
        "wljeskzntydaqfg\n" +
        "plxzvtwdrqosfckhnjb\n" +
        "\n" +
        "aswnqfrcoe\n" +
        "oecaqf\n" +
        "ziqayfjum\n" +
        "avfrq\n" +
        "\n" +
        "iortchugjyax\n" +
        "mlxsbgzrvfaun\n" +
        "\n" +
        "ispmrkfvyhczdotnjua\n" +
        "kqcvmrasoblntihzxufjydp\n" +
        "cptoryiszakdhjmuvfn\n" +
        "\n" +
        "qstwglyd\n" +
        "qylwdstg\n" +
        "tgsdqwyl\n" +
        "wsdygtql\n" +
        "\n" +
        "shcbwqgu\n" +
        "bdqmn\n" +
        "vaesbq\n" +
        "lrptqfijxy\n" +
        "qkz\n" +
        "\n" +
        "svoxw\n" +
        "zxwbkvo\n" +
        "owzxve\n" +
        "xwogbnvzk\n" +
        "vtwfqjiox\n" +
        "\n" +
        "wq\n" +
        "rwq\n" +
        "qw\n" +
        "\n" +
        "nrxyvf\n" +
        "yfpnrx\n" +
        "fnxpvyrj\n" +
        "edwsaytzfhnxr\n" +
        "\n" +
        "jdpfyteizvkc\n" +
        "ypjmnvlwtfdcezgk\n" +
        "\n" +
        "bcpwnkgsvtxdoryifh\n" +
        "gfscykroibnxdhtv\n" +
        "bgyjnckfsrziqvohxdtu\n" +
        "\n" +
        "jxwqdnocstrzvhybguilemf\n" +
        "bmcqdgrlznwsexfavhyioj\n" +
        "wxamfqjrobyzicesdnplgvh\n" +
        "ngjixrfmsvdopqbecwlyzh\n" +
        "gnfdcimovhbjxrszwyleq\n" +
        "\n" +
        "rpgdzmcneyjthsvflb\n" +
        "tnmfyjrzbosldg\n" +
        "ndszyijtbfrlgm\n" +
        "tzslbmrfoynqjdg\n" +
        "\n" +
        "rekgsioqlu\n" +
        "unjlczqkbdvgahm\n" +
        "qpxrtusklgyo\n" +
        "\n" +
        "iwupkfsxnoqzcd\n" +
        "pvzwkmdejybqhtrcn\n" +
        "zswapofucqgndk\n" +
        "ukqgpdlocnwz\n" +
        "\n" +
        "yxzpgn\n" +
        "xzypng\n" +
        "xyzpng\n" +
        "\n" +
        "ibg\n" +
        "igbf\n" +
        "igb\n" +
        "big\n" +
        "\n" +
        "krqgmdcbxeuvsaihj\n" +
        "jsiartydzuqhvowp\n" +
        "qvbrdskexjauih\n" +
        "\n" +
        "bgaoqndvurhy\n" +
        "ursayhgpqbonc\n" +
        "\n" +
        "nrzwfeqdmui\n" +
        "rdjmwnkzpq\n" +
        "\n" +
        "aihrwbyjzt\n" +
        "wcajbti\n" +
        "\n" +
        "sizktqxjyohd\n" +
        "khzqdtxosjyi\n" +
        "\n" +
        "qclmepht\n" +
        "qdplucnb\n" +
        "\n" +
        "maxvquihzfskdbglj\n" +
        "wvisljfgbkrmqzca\n" +
        "nafgikszlbqjvm\n" +
        "kfmsbcgvizalqj\n" +
        "\n" +
        "ub\n" +
        "beu\n" +
        "\n" +
        "dxhnelp\n" +
        "mpfiselg\n" +
        "lpexzoaytv\n" +
        "\n" +
        "gmuvyxln\n" +
        "wkxoegvjhumdal\n" +
        "\n" +
        "x\n" +
        "x\n" +
        "x\n" +
        "x\n" +
        "x\n" +
        "\n" +
        "skvxydbqmzehnlcwo\n" +
        "vcnkdequzxloghybwp\n" +
        "\n" +
        "uslq\n" +
        "sluq\n" +
        "qsul\n" +
        "osqul\n" +
        "\n" +
        "euknogsl\n" +
        "jbvrnkgoslu\n" +
        "npmcutyihaogwsxqdfl\n" +
        "\n" +
        "qbfoiukvea\n" +
        "pgdzhc\n" +
        "\n" +
        "njdlgbus\n" +
        "judbcghtnf\n" +
        "\n" +
        "calds\n" +
        "lcsa\n" +
        "\n" +
        "dvcnlxhkt\n" +
        "bvzhingdrykjsxo\n" +
        "vkphfxdn\n" +
        "\n" +
        "bsferyztuikaq\n" +
        "fsbayqukrtzeic\n" +
        "ebksiyzlqrfuta\n" +
        "\n" +
        "spmkwhd\n" +
        "nhbz\n" +
        "bqxclfh\n" +
        "hjnli\n" +
        "\n" +
        "hsmqoplv\n" +
        "hopqvsl\n" +
        "olbhfvwusp\n" +
        "hoqpslve\n" +
        "svoplnh\n" +
        "\n" +
        "tpnuwvzabcmjfiod\n" +
        "avwntjdbzcupfo\n" +
        "\n" +
        "bdvyenjktqcgawm\n" +
        "rvgteckqmb\n" +
        "kqrvmtfbgec\n" +
        "\n" +
        "fu\n" +
        "sdc\n" +
        "jzrginhoalw\n" +
        "\n" +
        "hpwdfomy\n" +
        "shwjzmpfikoydb\n" +
        "yfwmhdopl\n" +
        "yhwdmfpo\n" +
        "\n" +
        "q\n" +
        "q\n" +
        "m\n" +
        "h\n" +
        "m\n" +
        "\n" +
        "qg\n" +
        "gq\n" +
        "qg\n" +
        "\n" +
        "d\n" +
        "do\n" +
        "d\n" +
        "\n" +
        "pebzkhvxmicuwgoynrjdsf\n" +
        "dchofjsmzrkgwxpyvqeiunb\n" +
        "\n" +
        "ljfm\n" +
        "mflj\n" +
        "ljmf\n" +
        "mvjufl\n" +
        "mjfly\n" +
        "\n" +
        "juvli\n" +
        "luvji\n" +
        "lviuj\n" +
        "vliju\n" +
        "lijvu\n" +
        "\n" +
        "qyokiecwgxsdpf\n" +
        "pwqfselocinxgdky\n" +
        "yoksiqgwdecpfx\n" +
        "\n" +
        "y\n" +
        "xpofmyg\n" +
        "vyhz\n" +
        "y\n" +
        "yz\n" +
        "\n" +
        "rihacgdmbn\n" +
        "abcmigdhnr\n" +
        "ignabdmchr\n" +
        "gdhmirabnc\n" +
        "rdhganmicb\n" +
        "\n" +
        "bizqcode\n" +
        "zdp\n" +
        "dpazjrt\n" +
        "wzxd\n" +
        "\n" +
        "cmfihuwqnzbtglp\n" +
        "itnwhuzlpgjmfqcdb\n" +
        "\n" +
        "ut\n" +
        "ut\n" +
        "ut\n" +
        "ut\n" +
        "tud\n" +
        "\n" +
        "klhufpyioetxngj\n" +
        "jxuhfpiyntkgeo\n" +
        "hkefjnpgixuyto\n" +
        "igknoteuxpfhjy\n" +
        "\n" +
        "uysoaqjzmgcrvkdnlebpwtx\n" +
        "enlrwtxomaqjupvsczydkgb\n" +
        "vdsziegptqljwabxnoruycmk\n" +
        "\n" +
        "nycf\n" +
        "mcxo\n" +
        "\n" +
        "ytivwfslq\n" +
        "ftvqli\n" +
        "fvitquel\n" +
        "\n" +
        "nybhaiupejdxkgs\n" +
        "xyajdsbuekinp\n" +
        "ayjpbnuxksedcw\n" +
        "peynrkadsuzjxb\n" +
        "nugdjbypkxashe\n" +
        "\n" +
        "nvdaqfkbyomhxptiswugrzce\n" +
        "xzkhfsjotigcypdnmubavweqr\n" +
        "ndhyrzqaekivtxgcfwosubpm\n" +
        "cdzatkpnvesrqgomybuwxifh\n" +
        "\n" +
        "sujzvcnoy\n" +
        "zusnxef\n" +
        "tsqdwghnaulizp\n" +
        "yusnjbz\n" +
        "mosjenukz\n" +
        "\n" +
        "rqwov\n" +
        "vqdgorw\n" +
        "ovrwq\n" +
        "opwvqr\n" +
        "\n" +
        "dktvrwchflapu\n" +
        "prlxwcavdfsu\n" +
        "vadwuqfrpxlc\n" +
        "cwuvraplfd\n" +
        "\n" +
        "qsjpxud\n" +
        "qpdixsu\n" +
        "\n" +
        "xvktceduf\n" +
        "tuedxcrv\n" +
        "xcutdev\n" +
        "edvrxuyct\n" +
        "eqcdxtyuv\n" +
        "\n" +
        "sbmhyidelk\n" +
        "eldbhmsiky\n" +
        "hkmoyisxledb\n" +
        "kmebisyhdl\n" +
        "elihmyskdb\n" +
        "\n" +
        "ycnp\n" +
        "ycnqmsp\n" +
        "\n" +
        "rhyjefcnpsqt\n" +
        "fsqretnhjycp\n" +
        "efrjhqscptyn\n" +
        "qscfhrjlypetn\n" +
        "\n" +
        "jtwuhekpbqaoizgcdym\n" +
        "omuyzaiedpkwgsqhb\n" +
        "eghavourqipwmdnkbyz\n" +
        "\n" +
        "xyejzbknatlrimf\n" +
        "lrfyqejnxamzdktb\n" +
        "natmyzjxevqrfwhkbl\n" +
        "qmjfzrtlnkeaxby\n" +
        "ycblzpfmektoanjxgr\n" +
        "\n" +
        "quwatziscogfnj\n" +
        "hravz\n" +
        "xlbmkza\n" +
        "\n" +
        "qtjslp\n" +
        "czikofeuy\n" +
        "ptxbvwal\n" +
        "\n" +
        "icmd\n" +
        "ipc\n" +
        "oxftiscgzyb\n" +
        "ciej\n" +
        "nwkcvqi\n" +
        "\n" +
        "mk\n" +
        "o\n" +
        "dwxb\n" +
        "\n" +
        "rzg\n" +
        "rewg\n" +
        "rge\n" +
        "rg\n" +
        "rwg\n" +
        "\n" +
        "o\n" +
        "th\n" +
        "o\n" +
        "\n" +
        "jtkifz\n" +
        "ltmikzj\n" +
        "fceztlmipj\n" +
        "pjzati\n" +
        "jgzdbhsytwni\n" +
        "\n" +
        "ablqpzxmoingerywf\n" +
        "xpmfezbayrilngoqw\n" +
        "mixpnyqrfaeglbozw\n" +
        "\n" +
        "pjewrkfisbo\n" +
        "jkeaprhbfswog\n" +
        "tojwpfbsekr\n" +
        "fwbeprkjscmdo\n" +
        "\n" +
        "udpjifbsevlwqxgkmtrco\n" +
        "yimjwpcnukrsdavqxohf\n" +
        "\n" +
        "acrljesyth\n" +
        "aontchrvljy\n" +
        "talszhrbcfjqey\n" +
        "chrjtwyqla\n" +
        "mhxlytjuiagrpkdc\n" +
        "\n" +
        "ockyq\n" +
        "dy\n" +
        "\n" +
        "e\n" +
        "ex\n" +
        "\n" +
        "uz\n" +
        "zd\n" +
        "uhz\n" +
        "\n" +
        "rqvhze\n" +
        "hrezqv\n" +
        "zovfeqhr\n" +
        "\n" +
        "boekypjtz\n" +
        "zktoyjebp\n" +
        "epbktyojz\n" +
        "opbktycezj\n" +
        "\n" +
        "vpladrzxbwh\n" +
        "pvgizarljdxbwh\n" +
        "\n" +
        "soalndurh\n" +
        "ruhosadbmvf\n" +
        "arudhnos\n" +
        "lspqurhadoj\n" +
        "\n" +
        "ualpstjky\n" +
        "psujtykal\n" +
        "skaujpylt\n" +
        "tsapujkyl\n" +
        "\n" +
        "hxagklitebnmdrqcfwvsj\n" +
        "ehdxmkqaycvsonbrfwi\n" +
        "\n" +
        "xzfmroh\n" +
        "dntb\n" +
        "g\n" +
        "\n" +
        "vdmbkqil\n" +
        "sbkwqm\n" +
        "kqbyrxm\n" +
        "bkqsm\n" +
        "muwkqbzy\n" +
        "\n" +
        "qljpfbimaswex\n" +
        "lwmsbijafpq\n" +
        "bdalifmpwqsj\n" +
        "jlamqpiwfsb\n" +
        "\n" +
        "gtck\n" +
        "ckmwt\n" +
        "\n" +
        "wqvp\n" +
        "ws\n" +
        "wu\n" +
        "w\n" +
        "wu\n" +
        "\n" +
        "fglbvteoinduycjqksmxzrphwa\n" +
        "fixyhqwlnkszvoregcudbtpjma\n" +
        "\n" +
        "oqjb\n" +
        "gbkqj\n" +
        "jblq\n" +
        "qbj\n" +
        "\n" +
        "yiurdl\n" +
        "uidlyr\n" +
        "liuyrd\n" +
        "ruydneli\n" +
        "\n" +
        "qznajfvr\n" +
        "zrjnavfq\n" +
        "fjqrzanv\n" +
        "\n" +
        "ndwpjqyx\n" +
        "yzpdqcnmwxf\n" +
        "\n" +
        "avnxlomwtjdhqei\n" +
        "dqfxmreculykgvtjon\n" +
        "\n" +
        "fqotuvxki\n" +
        "ovywiuqkf\n" +
        "uiqhkofve\n" +
        "ioukvqf\n" +
        "quiwvftokp\n" +
        "\n" +
        "mcxhanksj\n" +
        "exnjhocfm\n" +
        "\n" +
        "m\n" +
        "m\n" +
        "s\n" +
        "m\n" +
        "m\n" +
        "\n" +
        "mkq\n" +
        "akmql\n" +
        "mkq\n" +
        "kqm\n" +
        "\n" +
        "zxldabvrtwoyicp\n" +
        "rlpbqfwdcovaet\n" +
        "crgujdvbkpswmolat\n" +
        "nwhdbcvpotalr\n" +
        "\n" +
        "asngcw\n" +
        "zxafhgp\n" +
        "yjegdutvorm\n" +
        "iqngs\n" +
        "nkgzx\n" +
        "\n" +
        "z\n" +
        "my\n" +
        "d\n" +
        "ohfc\n" +
        "s\n" +
        "\n" +
        "k\n" +
        "r\n" +
        "m\n" +
        "\n" +
        "ihelxwpygbo\n" +
        "oebglxywhupi\n" +
        "lgbxpiyhwo\n" +
        "biwoxgplshy\n" +
        "\n" +
        "ygqnkm\n" +
        "mknqg\n" +
        "nkqimgfz\n" +
        "gnqmk\n" +
        "glmnqk\n" +
        "\n" +
        "peax\n" +
        "ealx\n" +
        "eax\n" +
        "\n" +
        "whgsjnbd\n" +
        "whgsnjdb\n" +
        "wpgdhjnbs\n" +
        "\n" +
        "pbzmysjve\n" +
        "ebofukvyjpsh\n" +
        "jvyberpwstq\n" +
        "viyjcdesbwp\n" +
        "rpsvejbyi\n" +
        "\n" +
        "uymlzeihapo\n" +
        "yleivfaupz\n" +
        "pxzgqlayscbjeiwu\n" +
        "azeuiyfpl\n" +
        "ryphizkaeul\n" +
        "\n" +
        "kyiuectd\n" +
        "uykdeczi\n" +
        "\n" +
        "mf\n" +
        "zf\n" +
        "mf\n" +
        "fn\n" +
        "f\n" +
        "\n" +
        "lksmjwceqfpngyxzd\n" +
        "jmlcsvqdxkyuewngozbp\n" +
        "wlmeiyqdskgzhjpxnc\n" +
        "jdapwmsxznehqgkcly\n" +
        "\n" +
        "xujsqncmrgkflohyewzpa\n" +
        "qoatelunckgydifmhjpxrvwb\n" +
        "pykmhgazwjncuerloxfq\n" +
        "\n" +
        "efyo\n" +
        "nlcwbjef\n" +
        "\n" +
        "nzpwo\n" +
        "znwcop\n" +
        "\n" +
        "wxeguptj\n" +
        "mgstu\n" +
        "otgu\n" +
        "gut\n" +
        "utg\n" +
        "\n" +
        "tbpcqyvwizmgs\n" +
        "scmqvizpytgwb\n" +
        "iqzygwsptvcbm\n" +
        "ybimcptsgqvwz\n" +
        "\n" +
        "hlgwbevrqcjxsf\n" +
        "njifcqghxrvewtl\n" +
        "gwjcfmhqexlovrb\n" +
        "\n" +
        "xzs\n" +
        "zxs\n" +
        "\n" +
        "frjzu\n" +
        "uetgiqm\n" +
        "uaeov\n" +
        "sbgyqu\n" +
        "bquo\n" +
        "\n" +
        "yepgsojubnzxrhmtlfq\n" +
        "husqezbwxngmrtplf\n" +
        "gxqneopzrhdslbumft\n" +
        "hslbzwgeoiuqrnxftpm\n" +
        "fmunresxbhgaptqzvl\n" +
        "\n" +
        "opwuibl\n" +
        "piluwob\n" +
        "olwiubp\n" +
        "wibluop\n" +
        "\n" +
        "obvzhrmkn\n" +
        "oprkbvnmzh\n" +
        "zovnbhmrk\n" +
        "vnomkzjrbh\n" +
        "obmkrnzvh\n" +
        "\n" +
        "rbgsywpzifanclt\n" +
        "hfwndizxkjtsuypvcbra\n" +
        "cznwbamiyptrfs\n" +
        "\n" +
        "yopvb\n" +
        "obpy\n" +
        "ybop\n" +
        "oybp\n" +
        "\n" +
        "tcr\n" +
        "tc\n" +
        "tc\n" +
        "ct\n" +
        "ct\n" +
        "\n" +
        "owztrcxfgy\n" +
        "ftzlorxgwbmk\n" +
        "wrgoxtfz\n" +
        "\n" +
        "qd\n" +
        "zcn\n" +
        "mo\n" +
        "\n" +
        "jpghwqsofrcuatkexy\n" +
        "sfcxkwaoytjeurhpg\n" +
        "ycwtxehprjfaogsku\n" +
        "rjfognzhatpecwuykxs\n" +
        "\n" +
        "urtsinfxlmqgzhd\n" +
        "fsrhtuixzgqnmdl\n" +
        "rtuzixmsfqnhdlg\n" +
        "yqglzisofmtnrduhx\n" +
        "\n" +
        "iuawhprfkdqnjsxct\n" +
        "qihkjosclamtyuvbwnp\n" +
        "hsdipzjuetkcaqwn\n" +
        "zpsfhktcqujgixanw\n" +
        "\n" +
        "dpey\n" +
        "zjmyedpx\n" +
        "nepyd\n" +
        "dyep\n" +
        "epnyd\n" +
        "\n" +
        "luqyb\n" +
        "blqtuy\n" +
        "yjlubq\n" +
        "\n" +
        "niulkzgvmpyseqacdjrowb\n" +
        "lcaozsimjbuqdfygwvker\n" +
        "\n" +
        "gzyfw\n" +
        "zyfgw\n" +
        "yzgfw\n" +
        "wyzgf\n" +
        "\n" +
        "z\n" +
        "z\n" +
        "z\n" +
        "z\n" +
        "z\n" +
        "\n" +
        "ymfsvlrk\n" +
        "yfmsrvlk\n" +
        "fmvykslr\n" +
        "ksfrvlym\n" +
        "vrsklfbym\n" +
        "\n" +
        "ent\n" +
        "nwetal\n" +
        "tne\n" +
        "nte\n" +
        "\n" +
        "nbwkjt\n" +
        "wbtkj\n" +
        "\n" +
        "sydlfim\n" +
        "yixfumpt\n" +
        "ofkwymbaiz\n" +
        "qfyendmi\n" +
        "yfmix\n" +
        "\n" +
        "lrdzymgabtexswqn\n" +
        "xrotnmkzdlgqsc\n" +
        "\n" +
        "bilqfktvxanemzgusrph\n" +
        "snpakrugbyfmwhqxetizlv\n" +
        "mehpaftzvlsbqikngxur\n" +
        "\n" +
        "kxsnoemdalq\n" +
        "ubptrgfvdcyz\n" +
        "\n" +
        "xzvsnur\n" +
        "snrzu\n" +
        "\n" +
        "ejrnailgkmhutwbvdfpyz\n" +
        "tlmcgefjuvaiyrwkz\n" +
        "\n" +
        "ftlzhxs\n" +
        "ohxflzts\n" +
        "\n" +
        "kzijpbnmfhaxtvl\n" +
        "flibzjwhtamkxp\n" +
        "bskirxmthdjflozep\n" +
        "tujiphbfxmzkl\n" +
        "\n" +
        "ambtcpgq\n" +
        "qbmpgtca\n" +
        "abtqmpgc\n" +
        "mtpcagqb\n" +
        "\n" +
        "taofbg\n" +
        "tfoabg\n" +
        "outgafb\n" +
        "\n" +
        "biurh\n" +
        "hriqbu\n" +
        "biuhr\n" +
        "rbuzih\n" +
        "ubirh\n" +
        "\n" +
        "rvjxdbitgc\n" +
        "tbrgxjucvid\n" +
        "jmortivxcdbg\n" +
        "gbrjcvxtdi\n" +
        "\n" +
        "qvngfmuyozdbkwaphcr\n" +
        "haiufrkzvwydboqjp\n" +
        "wnukvpfzlhrayoqdb\n" +
        "zduckowqyebhfsrvpa\n" +
        "dvrqoswbpaehtyzfuk\n" +
        "\n" +
        "yzhmrogndc\n" +
        "fxzb\n" +
        "evkwjbpz\n" +
        "jatpvz\n" +
        "suqzbi\n" +
        "\n" +
        "rxfdvumlhntsowpiycabzgejq\n" +
        "iopsjqmnwhcfuargbytkxvzled\n" +
        "icaybhzfvpuoeswxqnrlmgdjt\n" +
        "sneioplcdjfxuvtazqbrgymhw\n" +
        "\n" +
        "xjas\n" +
        "fyhux\n" +
        "\n" +
        "gwistylekhruxovq\n" +
        "lythgqivuowksxer\n" +
        "igekwlosqturxvy\n" +
        "royckiudglevxwsqmt\n" +
        "\n" +
        "xvblauri\n" +
        "rduxqmnt\n" +
        "xzruo\n" +
        "uxqrjn\n" +
        "\n" +
        "bunsrlgk\n" +
        "qnyrc\n" +
        "rwnyq\n" +
        "\n" +
        "zkyqfrnbmuatojxvwihel\n" +
        "zeaxtqjonbrfuklmwivh\n" +
        "tkbsquaojwvnhzgeriplxmf\n" +
        "hzikjfvmtruabqexwlon\n" +
        "lqodamkfxjerunhzibtvw\n" +
        "\n" +
        "y\n" +
        "q\n" +
        "\n" +
        "c\n" +
        "cu\n" +
        "qkv\n" +
        "\n" +
        "ervnoqgafw\n" +
        "oscminrewf\n" +
        "wofjbr\n" +
        "\n" +
        "b\n" +
        "b\n" +
        "ro\n" +
        "b\n" +
        "b\n" +
        "\n" +
        "ylpedbjm\n" +
        "jmyqepfb\n" +
        "peyjbm\n" +
        "\n" +
        "srba\n" +
        "gioz\n" +
        "aluw\n" +
        "baseu\n" +
        "\n" +
        "wamvctoexzgf\n" +
        "bsyjrxdeo\n" +
        "\n" +
        "epbf\n" +
        "rfobeq\n" +
        "bfe\n" +
        "etfichnybuv\n" +
        "\n" +
        "idyq\n" +
        "lqiy\n" +
        "yqil\n" +
        "iyq\n" +
        "yqi\n" +
        "\n" +
        "dhkv\n" +
        "spcnm\n" +
        "\n" +
        "mpuijvlgbd\n" +
        "bdpfmreatciv\n" +
        "\n" +
        "phj\n" +
        "jph\n" +
        "pjh\n" +
        "jpbh\n" +
        "\n" +
        "hvox\n" +
        "odxh\n" +
        "\n" +
        "tkiamnuv\n" +
        "\n" +
        "enukxohqzridb\n" +
        "dioqhnrubkxze\n" +
        "xqokdubnirzhe\n" +
        "iudqxoknhrezb\n" +
        "hdxrnuqkbseozi\n" +
        "\n" +
        "zxjg\n" +
        "xnak\n" +
        "kix\n" +
        "\n" +
        "qoflemvucnta\n" +
        "lvaqmncftoeu\n" +
        "elqmofnvcuat\n" +
        "yvqlrcafenthom\n" +
        "vqotfncaelm\n" +
        "\n" +
        "czrtsdaiw\n" +
        "sziwdatcr\n" +
        "\n" +
        "vsytnpgefkwxqaouhcmb\n" +
        "oaeldkpvhbcryuxtfsi\n" +
        "ezxktcyfophsabvu\n" +
        "ctuaehvobkyspxf\n" +
        "yehbrcsovtakpxzuf\n" +
        "\n" +
        "wjrd\n" +
        "drjw\n" +
        "rdwj\n" +
        "djrw\n" +
        "wjdr\n" +
        "\n" +
        "t\n" +
        "v\n" +
        "t\n" +
        "d\n" +
        "\n" +
        "micqdwj\n" +
        "rqjmownes\n" +
        "pqtmwj\n" +
        "yxwjiadmq\n" +
        "\n" +
        "wmlsot\n" +
        "ufypiewba\n" +
        "vtsqzrwdk\n" +
        "\n" +
        "xd\n" +
        "ux\n" +
        "\n" +
        "gfyrh\n" +
        "vet\n" +
        "bml\n" +
        "pka\n" +
        "\n" +
        "konhiwejsydptz\n" +
        "htwiogdpnjsy\n" +
        "sqbfvoywhdjnxtiu\n" +
        "nstohyjidzwp\n" +
        "\n" +
        "oulvcfs\n" +
        "cfvslou\n" +
        "lvodsucf\n" +
        "tsvcuolf\n" +
        "sfoclvu\n" +
        "\n" +
        "omfdtxpnqgwhrlac\n" +
        "qtmxpdngcfarwolh\n" +
        "ptrlngqxchmaodfw\n" +
        "zxmdcqfrtlhgpaonw\n" +
        "mtrhldnwpqxgoacf\n" +
        "\n" +
        "hfmbnlwtujeqacxo\n" +
        "bjolymcdfhxaqwu\n" +
        "mcfahwxjsqboul\n" +
        "hyobucwmaqlxfj\n" +
        "\n" +
        "okxygwhp\n" +
        "wvkxgpho\n" +
        "xyufhgwkop\n" +
        "okgpyhwnbx\n" +
        "\n" +
        "ct\n" +
        "c\n" +
        "\n" +
        "mrajcxniesvqtzhygfkp\n" +
        "nmaxyrvsczhipkgejqfot\n" +
        "ecmirqgjkhftzpansx\n" +
        "uaesfjdmixkgqcpthlrzn\n" +
        "qnpojcfksgtmhzaxrie\n" +
        "\n" +
        "oinruztqxj\n" +
        "rvoumlcwdbik\n" +
        "\n" +
        "swa\n" +
        "sayj\n" +
        "rxygsab\n" +
        "rzlxs\n" +
        "usdqnecvmt\n" +
        "\n" +
        "kacytqiemxbwrl\n" +
        "nodjpvuhgt\n" +
        "\n" +
        "tu\n" +
        "pte\n" +
        "\n" +
        "nyat\n" +
        "nzft\n" +
        "rnftd\n" +
        "potnbg\n" +
        "\n" +
        "pu\n" +
        "up\n" +
        "pu\n" +
        "\n" +
        "swftrvkn\n" +
        "fnvwtriks\n" +
        "\n" +
        "zvukcgfm\n" +
        "prdgtfkqh\n" +
        "gvckxzf\n" +
        "fkgi\n" +
        "fkzg\n" +
        "\n" +
        "kyojecwftxlq\n" +
        "kymipznvgh\n" +
        "wjoukyse\n" +
        "\n" +
        "jikgxfnpl\n" +
        "zkupgjrxilmn\n" +
        "\n" +
        "l\n" +
        "l\n" +
        "ral\n" +
        "l\n" +
        "l\n" +
        "\n" +
        "feuprzgydcvmniqtbhwsloa\n" +
        "yzguptfnihbemvqsdjkxc\n" +
        "\n" +
        "wlpaenfhz\n" +
        "ehawliznq\n" +
        "\n" +
        "nw\n" +
        "bw\n" +
        "\n" +
        "vdtqpkxbrczjfiayumhgo\n" +
        "umoerhdfcazgtj\n" +
        "jldrhtzawcmfugo\n" +
        "zahcgrtdufjmo\n" +
        "muaglcntdjrfzoh\n" +
        "\n" +
        "fq\n" +
        "fq\n" +
        "vfq\n" +
        "\n" +
        "ldcsbpxaq\n" +
        "qcbalszxgd\n" +
        "\n" +
        "nzvuexwaqbtkjdhpfls\n" +
        "vnfdayzbxlqskjuhewp\n" +
        "\n" +
        "bejuodklarwyqmftv\n" +
        "wovrdtyqmbuf\n" +
        "bfoqtumdywrv\n" +
        "\n" +
        "pcatgvxsfnemhd\n" +
        "juyahm\n" +
        "\n" +
        "hsgfnxpyirz\n" +
        "pkychzfjasrqni\n" +
        "\n" +
        "jvhzlgfsreoaqimytdn\n" +
        "ltcaybovrmhinws\n" +
        "\n" +
        "hvpaxkrbyf\n" +
        "yprhbv\n" +
        "yhzvbpr\n" +
        "vpjhebymr\n" +
        "ypvbrh\n" +
        "\n" +
        "vxbshtzumdg\n" +
        "gzhdbkvnymt\n" +
        "mghlcvjibrqewao\n" +
        "\n" +
        "qwatcjvglnkoxbz\n" +
        "jlanewzf\n" +
        "ewryzpjnla\n" +
        "hapjrwlnsz\n" +
        "\n" +
        "wedijntshvckmuagqroyz\n" +
        "aygdzjuvqetrcnkmhiwos\n" +
        "\n" +
        "h\n" +
        "h\n" +
        "y\n" +
        "\n" +
        "tkzajcrnldp\n" +
        "ptrdkcezajnl\n" +
        "lrkcdjspnatz\n" +
        "\n" +
        "wpbavnk\n" +
        "pbnawkv\n" +
        "awmygpbfnqkv\n" +
        "wbvnkap\n" +
        "anwxvkbp\n" +
        "\n" +
        "ciojha\n" +
        "ergycubzds\n" +
        "\n" +
        "stxylmiduhbek\n" +
        "cdyluksmixh\n" +
        "leixuymskhd\n" +
        "\n" +
        "ckmb\n" +
        "hcbskxmj\n" +
        "kcmqba\n" +
        "ckubm\n" +
        "cbqkm\n" +
        "\n" +
        "zimehj\n" +
        "ekhjmz\n" +
        "zjmehx\n" +
        "ejzpmh\n" +
        "zadjhemo\n" +
        "\n" +
        "uiyfxjtwhzgam\n" +
        "rzsbqkl\n" +
        "\n" +
        "hij\n" +
        "cxhqiyj\n" +
        "\n" +
        "dc\n" +
        "di\n" +
        "nahc\n" +
        "kzegxs\n" +
        "hqd\n" +
        "\n" +
        "gwcmavtzudlyhbi\n" +
        "tczmgyaihdvwlu\n" +
        "\n" +
        "knmowxtrgysei\n" +
        "owhxyln\n" +
        "xnoyw\n" +
        "owxnvy\n" +
        "\n" +
        "awcdeyhxp\n" +
        "haidv\n" +
        "ajdzh\n" +
        "roamdnih\n" +
        "djhqba\n" +
        "\n" +
        "wikxntvrqobmslp\n" +
        "pvskylqtmiouxgerbzwa\n" +
        "\n" +
        "vtsodwufbxqagzjcirn\n" +
        "swbrznlvtdqgcuixoaj\n" +
        "xnbtowaqukpivrszcdjg\n" +
        "bdxiqvsoanwtgjcruz\n" +
        "\n" +
        "tknlrhyecmdpgavfwxiq\n" +
        "etgzofqjhbxisrlwakm\n" +
        "\n" +
        "qlapsncudif\n" +
        "lcpaubo\n" +
        "upcla\n" +
        "\n" +
        "q\n" +
        "q\n" +
        "q\n" +
        "q\n" +
        "\n" +
        "wthxvqcmkrnufij\n" +
        "cxumyjefhridbtk\n" +
        "itxcmpfjrukhv\n" +
        "usqhkciwmxjfzrt\n" +
        "\n" +
        "ovqmbrgjxzehayts\n" +
        "rvtojeyghszmbaqx\n" +
        "\n" +
        "wkdgt\n" +
        "dtgwk\n" +
        "ztcgwkdf\n" +
        "kdwtg\n" +
        "\n" +
        "bnqdcjklozxsvhaip\n" +
        "tsboknhvzmpdxa\n" +
        "bydonswmearvkzpxuh\n" +
        "\n" +
        "xouwszgd\n" +
        "zwuhdo\n" +
        "ouwhnczdxj\n" +
        "uodkfmqebwz\n" +
        "uzltdwon\n" +
        "\n" +
        "ea\n" +
        "zae\n" +
        "xae\n" +
        "eax\n" +
        "\n" +
        "glpjnaiuqhtcbvxkezsymow\n" +
        "myspguazhtokexidjvbfnrw\n" +
        "\n" +
        "gtiykcduephanslqxbvzf\n" +
        "acbtimgdpoefuvlyzxhn\n" +
        "rltacidghyevpxzbufn\n" +
        "\n" +
        "qbnlweychiavojgtpkxm\n" +
        "zwqlmncaxpouti\n" +
        "qntcxlismwoarp\n" +
        "\n" +
        "ywkxe\n" +
        "sywkex\n" +
        "yexwk\n" +
        "kyewx\n" +
        "wkxye\n" +
        "\n" +
        "uiegcdfsh\n" +
        "ugseifdnhc\n" +
        "defishcapgumb\n" +
        "\n" +
        "otaj\n" +
        "sjdaoqtbc\n" +
        "jatuo\n" +
        "\n" +
        "fymlhq\n" +
        "lifym\n" +
        "lpkmfhiy\n" +
        "muyfl\n" +
        "jlymwcsf\n" +
        "\n" +
        "ijlhukadenrqsvxgbo\n" +
        "kcidnlqrhubegxsjavom\n" +
        "lkjidgnrusewohbvxq\n" +
        "\n" +
        "kym\n" +
        "yk\n" +
        "yk\n" +
        "\n" +
        "yzdjwag\n" +
        "anxrbdiq\n" +
        "\n" +
        "bcmoyupkj\n" +
        "dhgzlx\n" +
        "\n" +
        "tjhagzlncpqe\n" +
        "hoqbcpzgujnt\n" +
        "\n" +
        "rtgifbclnsaehdqouyjk\n" +
        "wvjdyotzpmhubsaifkclqgre\n" +
        "tyjasohbcgxfukreqidl\n" +
        "\n" +
        "jarxzitusmqcd\n" +
        "wmupfblqejszyd\n" +
        "jdwuqsonmez\n" +
        "\n" +
        "lgfksnjtydbomcx\n" +
        "fmwgnksxbjcldeo\n" +
        "\n" +
        "kfiroa\n" +
        "frkayo\n" +
        "nkaflrwo\n" +
        "rceokmfat\n" +
        "frbktyaco\n" +
        "\n" +
        "msrjkzt\n" +
        "cer\n" +
        "rd\n" +
        "\n" +
        "agvf\n" +
        "afvg\n" +
        "gfav\n" +
        "vfag\n" +
        "\n" +
        "mjnwpxdzsg\n" +
        "lpdjfawbyiz\n" +
        "puvztdkojwh\n" +
        "gdzqretwpj\n" +
        "\n" +
        "yxnubi\n" +
        "xibenu\n" +
        "unbixy\n" +
        "\n" +
        "cfhxsvmuebgowktiyqz\n" +
        "hizkuswbefvcqtmoxlg\n" +
        "xtyogvkmbwscuizehfrq\n" +
        "gujihqmopzdfvwxksbtec\n" +
        "\n" +
        "vntrdelmwsfhk\n" +
        "stlgfmrkvdq\n" +
        "krmvtdslf\n" +
        "tksvfrdlm\n" +
        "efmrkvwdlts\n" +
        "\n" +
        "rujwcahnzpe\n" +
        "bfhzxdpjawtnu\n" +
        "\n" +
        "fxjnvwmbgrdeqlh\n" +
        "rdwgmhevljbxqfn\n" +
        "\n" +
        "orqvkhczeis\n" +
        "kieshrpomqvzt\n" +
        "svehozikrq\n" +
        "skrhezvqioc\n" +
        "\n" +
        "wxgqml\n" +
        "gxwslo\n" +
        "wgysplo\n" +
        "lhgzw\n" +
        "\n" +
        "oj\n" +
        "o\n" +
        "o\n" +
        "\n" +
        "u\n" +
        "u\n" +
        "jeu\n" +
        "u\n" +
        "u\n" +
        "\n" +
        "yiqxngbhocswjrfeudvt\n" +
        "ibygehckxwquomdnjp\n" +
        "bwcjixudyoqhgeanp\n" +
        "\n" +
        "hydfix\n" +
        "yihxd\n" +
        "yndxih\n" +
        "miwodlxsgehvytk\n" +
        "nxidhzyb\n" +
        "\n" +
        "qaz\n" +
        "zaquh\n" +
        "qazu\n" +
        "qclzba\n" +
        "\n" +
        "dvofyzwgjt\n" +
        "fowjydztgv\n" +
        "fdzjwgyvto\n" +
        "yfzdtvwgoj\n" +
        "vzfyotdgjw\n" +
        "\n" +
        "a\n" +
        "swa\n" +
        "a\n" +
        "a\n" +
        "a\n" +
        "\n" +
        "lf\n" +
        "f\n" +
        "f\n" +
        "f\n" +
        "\n" +
        "ehf\n" +
        "hef\n" +
        "ehf\n" +
        "hfe\n" +
        "ehf\n" +
        "\n" +
        "xpwgek\n" +
        "ujmts\n" +
        "\n" +
        "bfzl\n" +
        "nlkcqzb\n" +
        "\n" +
        "claus\n" +
        "uacse\n" +
        "vhucajsk\n" +
        "lacus\n" +
        "uasc\n" +
        "\n" +
        "bsdpxarynwm\n" +
        "ybawdxpsm\n" +
        "pmbdwasxqy\n" +
        "xwaqdbpyms\n" +
        "\n" +
        "ayodzjplqursvtciexbkfm\n" +
        "xisupbmazlvdkyjterfqc\n" +
        "\n" +
        "nqorupyxeicwljsbmhza\n" +
        "upcrsmlbojzqinxhyaew\n" +
        "pjysnwubqcomaheilzrx\n" +
        "\n" +
        "nfilv\n" +
        "fwbohynv\n" +
        "elkfvn\n" +
        "evanf\n" +
        "\n" +
        "ykzi\n" +
        "zjmck\n" +
        "zkm\n" +
        "pzk\n" +
        "kcz\n" +
        "\n" +
        "rcwpgdonmz\n" +
        "owzdyrcgvnm\n" +
        "wognrzycmd\n" +
        "rgblkszmodnciwxq\n" +
        "wgmornhdzc\n" +
        "\n" +
        "mu\n" +
        "um\n" +
        "rum\n" +
        "um\n" +
        "\n" +
        "wdjskfix\n" +
        "wdkxjfsi\n" +
        "ixwjrfdks\n" +
        "sdxwjkif\n" +
        "dsgklwhxifj\n" +
        "\n" +
        "wqvfmpctjga\n" +
        "mqcoafgntj\n" +
        "qjtgrfcam\n" +
        "fmawcjgqt\n" +
        "\n" +
        "fmqectkvuborwidgj\n" +
        "gobjtfrqkiumvc\n" +
        "hnmctagybvzpuriskfqo\n" +
        "\n" +
        "bpnwmazxdov\n" +
        "vnbxadleczwqo\n" +
        "wxodinbzav\n" +
        "xwnivzadbmo\n" +
        "dvoxzanbw\n" +
        "\n" +
        "pkumcqohndlxstvbijy\n" +
        "vxwuqmcydjzenpbtlriksf\n" +
        "\n" +
        "iduobhrnsat\n" +
        "otqruabhdnsz\n" +
        "ditrubnwhs\n" +
        "kvydthunsrpmcbgl\n" +
        "botunsrdh\n" +
        "\n" +
        "idyepasroklnwuczhqjg\n" +
        "orijbtsuvlqphfmcgya\n" +
        "\n" +
        "zohpdrxsm\n" +
        "dpjzohfmxr\n" +
        "prhgocxmzd\n" +
        "rmhzxlpobdw\n" +
        "zpocdymgxrh\n" +
        "\n" +
        "epjurdmqkiszfow\n" +
        "umpqkgcoeldf\n" +
        "dmekufqgpo\n" +
        "\n" +
        "jesvpxdraoyuzctklnqhgi\n" +
        "fbsqcraxhdzejgilytpvon\n" +
        "eshlqwkraypgojmxvzndcti\n" +
        "cdlieavgjphtqrusxnozy\n" +
        "cgotlexyhidaqsvpjmrknz\n" +
        "\n" +
        "n\n" +
        "a\n" +
        "n\n" +
        "\n" +
        "imwtv\n" +
        "iuw\n" +
        "riwx\n" +
        "ixpfruw\n" +
        "\n" +
        "ghuwqisktymp\n" +
        "syuwmgithn\n" +
        "gwyustmhij\n" +
        "trhwyafugsliom\n" +
        "sphtquwdzygmic\n" +
        "\n" +
        "mhrcbwsv\n" +
        "hmcvrws\n" +
        "hrwcmvs\n" +
        "\n" +
        "otm\n" +
        "bvtmo\n" +
        "rtosmuxc\n" +
        "\n" +
        "fcelpwgamhnquzbsrtdxivjk\n" +
        "tdjwzsaqhxunkfcvpbrmgil"}.b

function intersection(arrA,arrB){return arrA.filter(arrB.includes)}
function intersectionMultiple(arrs){
    return arrs.reduce(intersection)
}

function main(){
    const groups = INPUT.split("\n\n").map((line) =>line.split('\n'));
    const counts = groups.map((group) => {
        //let rec = {};
        /*for (const response of group){
            for (const letter of response){
                if (!rec[letter]) rec[letter] = 1;
                else rec[letter] ++;
            }
        }*/

        //return Object.keys(rec).length
        let a = group.map(b=> b.split(''))
        return intersectionMultiple(a).length
    })
    return counts.reduce((total, count) => total += count,0)

}
module.exports = main;
if (require.main === module) {
    console.log(main())
}
